<%@  page buffer="none" import="java.util.*,java.io.*,com.intershop.beehive.core.internal.template.*,com.intershop.beehive.core.internal.template.isml.*,com.intershop.beehive.core.capi.log.*,com.intershop.beehive.core.capi.resource.*,com.intershop.beehive.core.capi.util.UUIDMgr,com.intershop.beehive.core.capi.util.XMLHelper,com.intershop.beehive.foundation.util.*,com.intershop.beehive.core.internal.url.*,com.intershop.beehive.core.internal.resource.*,com.intershop.beehive.core.internal.wsrp.*,com.intershop.beehive.core.capi.pipeline.PipelineDictionary,com.intershop.beehive.core.capi.naming.NamingMgr,com.intershop.beehive.core.capi.pagecache.PageCacheMgr,com.intershop.beehive.core.capi.request.SessionMgr,com.intershop.beehive.core.internal.request.SessionMgrImpl,com.intershop.beehive.core.pipelet.PipelineConstants" extends="com.intershop.beehive.core.internal.template.AbstractTemplate" %><% 
boolean _boolean_result=false;
TemplateExecutionConfig context = getTemplateExecutionConfig();
createTemplatePageConfig(context.getServletRequest());
printHeader(out);
 %><% %><%! protected Boolean printTemplateMarker() { return Boolean.FALSE; } %><%%><%@ page contentType="text/html;charset=utf-8" %><%setEncodingType("text/html"); %><%@page import="com.intershop.beehive.core.capi.localization.LocaleInformation,com.intershop.beehive.core.capi.localization.LocaleMgr,com.intershop.beehive.core.capi.naming.NamingMgr"
%><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("Object"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",2,e);}if (_boolean_result) { %><%
	%><% _boolean_result=false;try {_boolean_result=((Boolean)(((((Boolean) (disableErrorMessages().isDefined(getObject("Locale")))).booleanValue() && ((Boolean) (disableErrorMessages().isDefined(getObject("Object:Description(Locale)")))).booleanValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",3,e);}if (_boolean_result) { %><%
		%><% {Object temp_obj = (getObject("Object:Description(Locale)")); getPipelineDictionary().put("ObjectPromotionDescription", temp_obj);} %><%
	%><% } else { %><%
		LocaleMgr localeMgr = (LocaleMgr) NamingMgr.getInstance().lookupManager(LocaleMgr.REGISTRY_NAME);
		LocaleInformation locale = localeMgr.getLeadLocale();
		getPipelineDictionary().put("LeadLocale", locale);
		%><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("Object:Description(LeadLocale)"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",9,e);}if (_boolean_result) { %><%
			%><% {Object temp_obj = (context.getFormattedValue(getObject("Object:Description(LeadLocale)"),null) + context.getFormattedValue(" (Language missing)",null)); getPipelineDictionary().put("ObjectPromotionDescription", temp_obj);} %><%
		%><% } else {_boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("Object:Description"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",11,e);}if (_boolean_result) { %><%
			%><% {Object temp_obj = (context.getFormattedValue(getObject("Object:Description"),null) + context.getFormattedValue(" (Language missing)",null)); getPipelineDictionary().put("ObjectPromotionDescription", temp_obj);} %><%
		%><% } else {_boolean_result=false;try {_boolean_result=((Boolean)(((((Boolean) (disableErrorMessages().isDefined(getObject("Object:Id")))).booleanValue() && ((Boolean) (((!(context.getFormattedValue(getObject("Object:Id"),null).equals(context.getFormattedValue("",null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",13,e);}if (_boolean_result) { %><%
		    %><% {Object temp_obj = (context.getFormattedValue(getObject("Object:Id"),null) + context.getFormattedValue(" (Name missing)",null)); getPipelineDictionary().put("ObjectPromotionDescription", temp_obj);} %><%
		%><% } else {_boolean_result=false;try {_boolean_result=((Boolean)(((((Boolean) (disableErrorMessages().isDefined(getObject("Object:ID")))).booleanValue() && ((Boolean) (((!(context.getFormattedValue(getObject("Object:ID"),null).equals(context.getFormattedValue("",null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",15,e);}if (_boolean_result) { %><%
			%><% {Object temp_obj = (context.getFormattedValue(getObject("Object:ID"),null) + context.getFormattedValue(" (Name missing)",null)); getPipelineDictionary().put("ObjectPromotionDescription", temp_obj);} %><%
		%><% } else { %><%
			%><% {Object temp_obj = (context.getFormattedValue(getObject("Object:UUID"),null) + context.getFormattedValue(" (Name missing)",null)); getPipelineDictionary().put("ObjectPromotionDescription", temp_obj);} %><%
		%><% }}}} %><%
	%><% } %><%
	%><% _boolean_result=false;try {_boolean_result=((Boolean)((((Boolean) ((((context.getFormattedValue(getObject("Print"),null).equals(context.getFormattedValue("false",null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue() ? Boolean.FALSE : Boolean.TRUE) )).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",21,e);}if (_boolean_result) { %><% {String value = null;try{value=context.getFormattedValue(getObject("ObjectPromotionDescription"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {21}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %><% } %><%
%><% } %><% printFooter(out); %>