exec ddl.drop_table('INVALIDATEDPAGECACHESEARCHWORD')
/

CREATE TABLE INVALIDATEDPAGECACHESEARCHWORD
(
    "INVALIDATIONTIME" TIMESTAMP(9),
    "SEARCHWORD" VARCHAR2(256 CHAR),
    "DOMAINID" VARCHAR2(28 CHAR),
    "UUID" VARCHAR2(28 CHAR),
    PRIMARY KEY ("INVALIDATIONTIME", "DOMAINID","SEARCHWORD", "UUID")
)
ORGANIZATION INDEX
/

COMMENT ON TABLE INVALIDATEDPAGECACHESEARCHWORD IS 'core'
/
