<%@  page buffer="none" import="java.util.*,java.io.*,com.intershop.beehive.core.internal.template.*,com.intershop.beehive.core.internal.template.isml.*,com.intershop.beehive.core.capi.log.*,com.intershop.beehive.core.capi.resource.*,com.intershop.beehive.core.capi.util.UUIDMgr,com.intershop.beehive.core.capi.util.XMLHelper,com.intershop.beehive.foundation.util.*,com.intershop.beehive.core.internal.url.*,com.intershop.beehive.core.internal.resource.*,com.intershop.beehive.core.internal.wsrp.*,com.intershop.beehive.core.capi.pipeline.PipelineDictionary,com.intershop.beehive.core.capi.naming.NamingMgr,com.intershop.beehive.core.capi.pagecache.PageCacheMgr,com.intershop.beehive.core.capi.request.SessionMgr,com.intershop.beehive.core.internal.request.SessionMgrImpl,com.intershop.beehive.core.pipelet.PipelineConstants" extends="com.intershop.beehive.core.internal.template.AbstractTemplate" %><% 
boolean _boolean_result=false;
TemplateExecutionConfig context = getTemplateExecutionConfig();
createTemplatePageConfig(context.getServletRequest());
printHeader(out);
 %><% %><%@ page contentType="text/html;charset=utf-8" %><%setEncodingType("text/html"); %><% {out.flush();processLocalIncludeByServer((com.intershop.beehive.core.capi.request.ServletResponse)response,"modules/Modules", null, "2");} %><div class="modal-dialog">
<div class="modal-content">
<div class="modal-header">
<button type="button" id="emailWishlistClose" class="close" data-dismiss="modal" title="<% {out.write(localizeISText("dialog.close.text","",null,null,null,null,null,null,null,null,null,null,null));} %>" aria-label="<% {out.write(localizeISText("dialog.close.text","",null,null,null,null,null,null,null,null,null,null,null));} %>"><span aria-hidden="true">&times;</span></button>
<h2 class="modal-title"><% {out.write(localizeISText("account.wishlist.email.heading","",null,null,null,null,null,null,null,null,null,null,null));} %></h2>
</div><% _boolean_result=false;try {_boolean_result=((Boolean)((((((Boolean) getObject("EmailWishlistForm:Submitted")).booleanValue() && ((Boolean) ((((Boolean) getObject("EmailWishlistForm:Invalid")).booleanValue() ? Boolean.FALSE : Boolean.TRUE) )).booleanValue()) ? Boolean.TRUE : Boolean.FALSE)))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",11,e);}if (_boolean_result) { %><% {try{executePipeline("DetermineRepositories-Channel",java.util.Collections.emptyMap(),"RepositoriesDictionary");}catch(Exception e){Logger.error(this,"ISPIPELINE failed. Line: 12.",e);}} %><% {Object temp_obj = (getObject("RepositoriesDictionary:Repository:DisplayName")); getPipelineDictionary().put("ChannelName", temp_obj);} %><% {Object temp_obj = (replace(context.getFormattedValue(encodeString(context.getFormattedValue(localizeTextEx(context.getFormattedValue("account.wishlist.email.recommend.subject",null),new ParameterList().addParameter(getObject("ChannelName"))),null),(String)("url")),null),(String)("\\+"),(String)("%20"))); getPipelineDictionary().put("EmailAFriendSubject", temp_obj);} %><% processOpenTag(response, pageContext, "setcanonicallink", new TagParameter[] {
new TagParameter("scope","request"),
new TagParameter("name","CurrentWishlistURL"),
new TagParameter("action","ViewWishlist-View"),
new TagParameter("parameters",new ParameterList().addParameter(context.getFormattedValue("WishlistID",null),context.getFormattedValue(getObject("WishlistBO:ID"),null)).addParameter(context.getFormattedValue("SecureCode",null),context.getFormattedValue(getObject("SecureCode"),null)).addParameter(context.getFormattedValue("UserID",null),context.getFormattedValue(getObject("CurrentUser:ID"),null)))}, 15); %><% _boolean_result=false;try {_boolean_result=((Boolean)(((!(context.getFormattedValue(getObject("EmailWishlistForm:EmailMessage:Value"),null).equals(context.getFormattedValue("",null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",20,e);}if (_boolean_result) { %><% {Object temp_obj = (context.getFormattedValue(getObject("EmailWishlistForm:EmailMessage:Value"),null) + context.getFormattedValue(" ",null) + context.getFormattedValue(getObject("WishlistBO:Name"),null) + context.getFormattedValue(" ",null) + context.getFormattedValue(getObject("CurrentWishlistURL"),null)); getPipelineDictionary().put("EmailAFriendBody", temp_obj);} %><% } else { %><% {Object temp_obj = (replace(context.getFormattedValue(encodeString(context.getFormattedValue(localizeTextEx(context.getFormattedValue("account.wishlist.email.recommend.text",null),new ParameterList().addParameter(getObject("WishlistBO:Name")).addParameter(getObject("CurrentWishlistURL"))),null),(String)("url")),null),(String)("\\+"),(String)("%20"))); getPipelineDictionary().put("EmailAFriendBody", temp_obj);} %><% } %><div class="modal-body">
<a href="mailto:<%=context.getFormattedValue(getObject("MailTo"),null)%>?subject=<%=context.getFormattedValue(getObject("EmailAFriendSubject"),null)%>&body=<%=context.getFormattedValue(getObject("EmailAFriendBody"),null)%>">
<p><% {out.write(localizeISText("account.wishlist.email.thankyou_message","",null,null,null,null,null,null,null,null,null,null,null));} %></p>
</a>
</div>
<script type="text/javascript">
window.location = 'mailto:' + '<%=context.getFormattedValue(getObject("MailTo"),null)%>' + '?subject=' + '<%=context.getFormattedValue(getObject("EmailAFriendSubject"),null)%>' + '&body=' + '<%=context.getFormattedValue(getObject("EmailAFriendBody"),null)%>';
$("<%=context.getFormattedValue("#",null)%>emailWishlistClose").click();
</script>
<div class="modal-footer">
<a href="<%=context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewWishlist-View",null))),(new URLParameterSet().addURLParameter(context.getFormattedValue("WishlistID",null),context.getFormattedValue(getObject("WishlistBO:ID"),null)))),null)%>" class="btn btn-default"><% {out.write(localizeISText("account.wishlist.email.close_window_button.text","",null,null,null,null,null,null,null,null,null,null,null));} %></a>
</div><% } else { %><% URLPipelineAction action18 = new URLPipelineAction(context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewWishlist-EmailWishlist",null)))),null));String site18 = null;String serverGroup18 = null;String actionValue18 = context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewWishlist-EmailWishlist",null)))),null);if (site18 == null){  site18 = action18.getDomain();  if (site18 == null)  {      site18 = com.intershop.beehive.core.capi.request.Request.getCurrent().getRequestSite().getDomainName();  }}if (serverGroup18 == null){  serverGroup18 = action18.getServerGroup();  if (serverGroup18 == null)  {      serverGroup18 = com.intershop.beehive.core.capi.request.Request.getCurrent().getRequestSite().getServerGroup();  }}out.print("<form");out.print(" method=\"");out.print("post");out.print("\"");out.print(" action=\"");out.print(context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewWishlist-EmailWishlist",null)))),null));out.print("\"");out.print(" name=\"");out.print("email-wishlist-form");out.print("\"");out.print(" data-hijax=\"");out.print("true");out.print("\"");out.print(" class=\"");out.print("form-horizontal bv-form");out.print("\"");out.print(">");out.print(context.prepareWACSRFTag(actionValue18, site18, serverGroup18,true)); %><div class="modal-body">
<p class="indicates-required"><span class="required">*</span><% {out.write(localizeISText("account.wishlist.required_field.text","",null,null,null,null,null,null,null,null,null,null,null));} %></p><% _boolean_result=false;try {_boolean_result=((Boolean)(getObject("EmailWishlistForm:Invalid"))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",46,e);}if (_boolean_result) { %><div class="alert alert-danger"><% {out.write(localizeISText("account.wishlist.email.form_error","",null,null,null,null,null,null,null,null,null,null,null));} %></div><% } %><input type="hidden" name="WishlistID" value="<% {String value = null;try{value=context.getFormattedValue(getObject("WishlistID"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {52}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>" />
<div class="form-group <% _boolean_result=false;try {_boolean_result=((Boolean)(getObject("EmailWishlistForm:FriendsEmails:Invalid"))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",53,e);}if (_boolean_result) { %>server-error<% } %>">
<label class="control-label col-sm-4"><% {out.write(localizeISText("account.wishlist.friend_email.label","",null,null,null,null,null,null,null,null,null,null,null));} %><span class="required">*</span></label>
<div class="col-sm-8">
<input type="email" class="form-control" 
name="<% {String value = null;try{value=context.getFormattedValue(getObject("EmailWishlistForm:FriendsEmails:QualifiedName"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {57}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>" 
value="<% {String value = null;try{value=context.getFormattedValue(getObject("EmailWishlistForm:FriendsEmails:Value"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {58}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>" 
maxlength="256" 
data-bv-emailaddress-message="<% {out.write(localizeISText("account.update_email.email.error.email","",null,null,null,null,null,null,null,null,null,null,null));} %>"
required 
data-bv-notempty-message="<% {out.write(localizeISText("account.update_email.email.error.notempty","",null,null,null,null,null,null,null,null,null,null,null));} %>" />
<small class="input-help"><% {out.write(localizeISText("account.wishlist.separate_multiple_emails_note","",null,null,null,null,null,null,null,null,null,null,null));} %></small>
</div>
</div>
<div class="form-group <% _boolean_result=false;try {_boolean_result=((Boolean)(getObject("EmailWishlistForm:EmailMessage:Invalid"))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",67,e);}if (_boolean_result) { %>server-error<% } %>">
<label class="control-label col-sm-4"><% {out.write(localizeISText("account.wishlist.personalized_message.label","",null,null,null,null,null,null,null,null,null,null,null));} %></label>
<div class="col-sm-8">
<textarea class="form-control"
maxlength="30000"
name="<% {String value = null;try{value=context.getFormattedValue(getObject("EmailWishlistForm:EmailMessage:QualifiedName"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {72}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>"
data-charactercounter="cCounter<% {String value = null;try{value=context.getFormattedValue(getObject("EmailWishlistForm:EmailMessage:QualifiedName"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {73}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>"
><% {String value = null;try{value=context.getFormattedValue(getObject("EmailWishlistForm:EmailMessage:Value"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {74}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %></textarea>
<small class="input-help"><% {out.write(localizeISText("checkout.shipping_method.instructions_max_limit.pre.text","",null,null,null,null,null,null,null,null,null,null,null));} %> <span id="cCounter<% {String value = null;try{value=context.getFormattedValue(getObject("EmailWishlistForm:EmailMessage:QualifiedName"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {75}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>"></span> <% {out.write(localizeISText("checkout.shipping_method.instructions_max_limit.post.text","",null,null,null,null,null,null,null,null,null,null,null));} %></small>
</div>
</div>
<p class="help-block"><% {out.write(localizeISText("account.wishlist.disclaimer.text","",null,null,null,null,null,null,null,null,null,null,null));} %> <a href="<%=context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewContent-Start",null))),(new URLParameterSet().addURLParameter(context.getFormattedValue("PageletEntryPointID",null),context.getFormattedValue("systempage.privacyPolicy.pagelet2-Page",null)))),null)%>"><% {out.write(localizeISText("account.wishlist.disclaimer.text.privacy_policy","",null,null,null,null,null,null,null,null,null,null,null));} %></a> <% {out.write(localizeISText("account.wishlist.disclaimer.text.suffix","",null,null,null,null,null,null,null,null,null,null,null));} %><br /><% {out.write(localizeISText("account.wishlist.disclaimer.text2","",null,null,null,null,null,null,null,null,null,null,null));} %></p>
</div>
<div class="modal-footer">
<button type="submit" class="btn btn-primary" name="sendMail" value="true"><% {out.write(localizeISText("account.wishlist.send_mail.button.text","",null,null,null,null,null,null,null,null,null,null,null));} %></button>
<button type="button" class="btn btn-default" data-dismiss="modal" name="cancel"><% {out.write(localizeISText("account.wishlist.cancel.button.text","",null,null,null,null,null,null,null,null,null,null,null));} %></button>
</div><% out.print("</form>"); %><% } %></div>
</div><% printFooter(out); %>