<%@  page buffer="none" import="java.util.*,java.io.*,com.intershop.beehive.core.internal.template.*,com.intershop.beehive.core.internal.template.isml.*,com.intershop.beehive.core.capi.log.*,com.intershop.beehive.core.capi.resource.*,com.intershop.beehive.core.capi.util.UUIDMgr,com.intershop.beehive.core.capi.util.XMLHelper,com.intershop.beehive.foundation.util.*,com.intershop.beehive.core.internal.url.*,com.intershop.beehive.core.internal.resource.*,com.intershop.beehive.core.internal.wsrp.*,com.intershop.beehive.core.capi.pipeline.PipelineDictionary,com.intershop.beehive.core.capi.naming.NamingMgr,com.intershop.beehive.core.capi.pagecache.PageCacheMgr,com.intershop.beehive.core.capi.request.SessionMgr,com.intershop.beehive.core.internal.request.SessionMgrImpl,com.intershop.beehive.core.pipelet.PipelineConstants" extends="com.intershop.beehive.core.internal.template.AbstractTemplate" %><% 
boolean _boolean_result=false;
TemplateExecutionConfig context = getTemplateExecutionConfig();
createTemplatePageConfig(context.getServletRequest());
printHeader(out);
 %>
<% %><%@ page contentType="text/html;charset=utf-8" %><%setEncodingType("text/html"); %><%
PipelineDictionary dict = getPipelineDictionary();
String key = null;
Object val = null;
int i = 1;
while ((key=dict.get("parametername"+i))!=null){
	val = dict.get("parametervalue"+i);
	dict.put(key, val);
	i++;
}
%><% _boolean_result=false;try {_boolean_result=((Boolean)((((context.getFormattedValue(getObject("previewError"),null).equals(context.getFormattedValue("PREVIEW_GENERAL_ERROR",null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",12,e);}if (_boolean_result) { %>
<% {out.write(localizeISText("PreviewError.AGeneralErrorOccurredDuringPreview","",null,null,null,null,null,null,null,null,null,null,null));} %>
<% } else {_boolean_result=false;try {_boolean_result=((Boolean)((((context.getFormattedValue(getObject("previewError"),null).equals(context.getFormattedValue("PREVIEW_DEFAULT_APPLICATION_NOT_PREVIEWABLE_ERROR",null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",14,e);}if (_boolean_result) { %>
<% {out.write(localizeISText("PreviewError.YouCannotPreviewThisPromotion","",null,null,null,null,null,null,null,null,null,null,null));} %>
<% } else {_boolean_result=false;try {_boolean_result=((Boolean)((((context.getFormattedValue(getObject("previewError"),null).equals(context.getFormattedValue("PREVIEW_APPLICATION_NOT_PREVIEWABLE_ERROR",null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",16,e);}if (_boolean_result) { %>
<% {out.write(localizeISText("PreviewError.TheSelectedApplicationIsNotAvailable","",null,null,null,null,null,null,null,null,null,null,null));} %>&nbsp;<a href="<%=context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewAccount-Show",null)))),null)%>" class="action_link fielditem_comment"><% {out.write(localizeISText("PreviewError.SelectApplication.link","",null,null,null,null,null,null,null,null,null,null,null));} %></a>
<% } else {_boolean_result=false;try {_boolean_result=((Boolean)((((context.getFormattedValue(getObject("previewError"),null).equals(context.getFormattedValue("PREVIEW_CHANNEL_NOT_DEFINED_ERROR",null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",18,e);}if (_boolean_result) { %>
<% {out.write(localizeISText("PreviewError.ToPreviewTheSelectedObjectPreviewChannelMustBeSelected.link","",null,null,null,null,null,null,null,null,null,null,null));} %>&nbsp;<a href="<%=context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewContentPreferences-ChannelList",null)))),null)%>" class="action_link fielditem_comment"><% {out.write(localizeISText("PreviewError.SelectChannel.link","",null,null,null,null,null,null,null,null,null,null,null));} %></a>
<% } else {_boolean_result=false;try {_boolean_result=((Boolean)((((context.getFormattedValue(getObject("previewError"),null).equals(context.getFormattedValue("PREVIEW_PRODUCT_NOT_AVAILABLE_ERROR",null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",20,e);}if (_boolean_result) { %>
<% {out.write(localizeISText("PreviewError.ToPreviewTheProductItMustBeSharedToPreviewChannel.link","",null,null,null,null,null,null,null,null,null,null,null));} %>&nbsp;<a href="<%=context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewProductSharing-Overview",null)))),null)%>" class="action_link fielditem_comment"><% {out.write(localizeISText("PreviewError.ShareProduct.link","",null,null,null,null,null,null,null,null,null,null,null));} %></a>
<% } else {_boolean_result=false;try {_boolean_result=((Boolean)((((context.getFormattedValue(getObject("previewError"),null).equals(context.getFormattedValue("PREVIEW_PRODUCT_FROM_MASTER_NOT_ONLINE_ERROR",null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",22,e);}if (_boolean_result) { %>
<% {out.write(localizeISText("PreviewError.ThisSharedProductIsCurrentlyNotOnlineInPreviewChannel.link","",null,null,null,null,null,null,null,null,null,null,null));} %>
<% } else {_boolean_result=false;try {_boolean_result=((Boolean)((((context.getFormattedValue(getObject("previewError"),null).equals(context.getFormattedValue("PREVIEW_PRODUCT_NOT_ONLINE_ERROR",null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",24,e);}if (_boolean_result) { %>
<% {out.write(localizeISText("PreviewError.ThisProductIsCurrentlyNotOnline.link","",null,null,null,null,null,null,null,null,null,null,null));} %>
<% } else {_boolean_result=false;try {_boolean_result=((Boolean)((((context.getFormattedValue(getObject("previewError"),null).equals(context.getFormattedValue("PREVIEW_PRODUCT_ONLINE_BUT_EXPIRED_ERROR",null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",26,e);}if (_boolean_result) { %>
<% {out.write(localizeISText("PreviewError.ThisProductIsCurrentlyOnlineButHasExpired.link","",null,null,null,null,null,null,null,null,null,null,null));} %>
<% } else {_boolean_result=false;try {_boolean_result=((Boolean)((((context.getFormattedValue(getObject("previewError"),null).equals(context.getFormattedValue("PREVIEW_PRODUCT_FROM_MASTER_ONLINE_BUT_EXPIRED_ERROR",null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",28,e);}if (_boolean_result) { %>
<% {out.write(localizeISText("PreviewError.InTheSelectedChannelTheProductIsOnlineButExpired.link","",null,null,null,null,null,null,null,null,null,null,null));} %>
<% } else {_boolean_result=false;try {_boolean_result=((Boolean)((((context.getFormattedValue(getObject("previewError"),null).equals(context.getFormattedValue("PREVIEW_CATEGORY_FROM_MASTER_NOT_ONLINE_ERROR",null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",30,e);}if (_boolean_result) { %>
<% {out.write(localizeISText("PreviewError.InTheSelectedChannelTheCategoryIsNotOnline.link","",null,null,null,null,null,null,null,null,null,null,null));} %>
<% } else {_boolean_result=false;try {_boolean_result=((Boolean)((((context.getFormattedValue(getObject("previewError"),null).equals(context.getFormattedValue("PREVIEW_CATEGORY_NOT_ONLINE_ERROR",null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",32,e);}if (_boolean_result) { %>
<% {out.write(localizeISText("PreviewError.TheCategoryIsNotOnlineNow.link","",null,null,null,null,null,null,null,null,null,null,null));} %>
<% } else {_boolean_result=false;try {_boolean_result=((Boolean)((((context.getFormattedValue(getObject("previewError"),null).equals(context.getFormattedValue("PREVIEW_CATALOG_FROM_MASTER_NOT_ONLINE_ERROR",null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",34,e);}if (_boolean_result) { %>
<% {out.write(localizeISText("PreviewError.InTheSelectedChannelTheCatalogIsNotOnline.link","",null,null,null,null,null,null,null,null,null,null,null));} %>
<% } else {_boolean_result=false;try {_boolean_result=((Boolean)((((context.getFormattedValue(getObject("previewError"),null).equals(context.getFormattedValue("PREVIEW_CATALOG_NOT_ONLINE_ERROR",null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",36,e);}if (_boolean_result) { %>
<% {out.write(localizeISText("PreviewError.TheCatalogIsNotOnline.link","",null,null,null,null,null,null,null,null,null,null,null));} %>
<% } else {_boolean_result=false;try {_boolean_result=((Boolean)((((context.getFormattedValue(getObject("previewError"),null).equals(context.getFormattedValue("PREVIEW_CATALOG_NOT_SHARED_TO_CHANNEL_ERROR",null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",38,e);}if (_boolean_result) { %>
<% {out.write(localizeISText("PreviewError.TheCatalogIsNotSharedToThePreviewChannel.link","",null,null,null,null,null,null,null,null,null,null,null));} %> &quot;<% {String value = null;try{value=context.getFormattedValue(getObject("MasterPageEditingChannel:DisplayName"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {39}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>&quot;.&nbsp;<a href="<%=context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewCatalogChannelList-ListAll",null))),(new URLParameterSet().addURLParameter(context.getFormattedValue("CatalogCatergoryID",null),context.getFormattedValue(getObject("CatalogCategoryID"),null))).addURLParameter(context.getFormattedValue("CatalogUUID",null),context.getFormattedValue(getObject("CatalogUUID"),null))),null)%>" class="action_link fielditem_comment"><% {out.write(localizeISText("PreviewError.ShareCatalog.link","",null,null,null,null,null,null,null,null,null,null,null));} %></a>
<% } else {_boolean_result=false;try {_boolean_result=((Boolean)((((context.getFormattedValue(getObject("previewError"),null).equals(context.getFormattedValue("PROMOTION_HAS_EXPIRED_ERROR",null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",40,e);}if (_boolean_result) { %>
<% {out.write(localizeISText("PreviewError.YouCannotPreviewThisPromotionBecauseExpired.link","",null,null,null,null,null,null,null,null,null,null,null));} %>
<% } else {_boolean_result=false;try {_boolean_result=((Boolean)((((context.getFormattedValue(getObject("previewError"),null).equals(context.getFormattedValue("ABTEST_HAS_EXPIRED_ERROR",null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",42,e);}if (_boolean_result) { %>
<% {out.write(localizeISText("PreviewError.YouCannotPreviewThisABTestBecauseExpired.link","",null,null,null,null,null,null,null,null,null,null,null));} %>
<% } else {_boolean_result=false;try {_boolean_result=((Boolean)((((context.getFormattedValue(getObject("previewError"),null).equals(context.getFormattedValue("CAMPAIGN_HAS_EXPIRED_ERROR",null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",44,e);}if (_boolean_result) { %>
<% {out.write(localizeISText("PreviewError.YouCannotPreviewThisCampaignBecauseExpired.link","",null,null,null,null,null,null,null,null,null,null,null));} %>
<% } else { %>
<% {out.write(localizeISText("PreviewError.PreviewForThisProductFailed.link","",null,null,null,null,null,null,null,null,null,null,null));} %>
<% }}}}}}}}}}}}}}}}} %>
<% printFooter(out); %>