<%@  page buffer="none" import="java.util.*,java.io.*,com.intershop.beehive.core.internal.template.*,com.intershop.beehive.core.internal.template.isml.*,com.intershop.beehive.core.capi.log.*,com.intershop.beehive.core.capi.resource.*,com.intershop.beehive.core.capi.util.UUIDMgr,com.intershop.beehive.core.capi.util.XMLHelper,com.intershop.beehive.foundation.util.*,com.intershop.beehive.core.internal.url.*,com.intershop.beehive.core.internal.resource.*,com.intershop.beehive.core.internal.wsrp.*,com.intershop.beehive.core.capi.pipeline.PipelineDictionary,com.intershop.beehive.core.capi.naming.NamingMgr,com.intershop.beehive.core.capi.pagecache.PageCacheMgr,com.intershop.beehive.core.capi.request.SessionMgr,com.intershop.beehive.core.internal.request.SessionMgrImpl,com.intershop.beehive.core.pipelet.PipelineConstants" extends="com.intershop.beehive.core.internal.template.AbstractTemplate" %><% 
boolean _boolean_result=false;
TemplateExecutionConfig context = getTemplateExecutionConfig();
createTemplatePageConfig(context.getServletRequest());
printHeader(out);
 %><% %><%@ page contentType="text/html;charset=utf-8" %><%setEncodingType("text/html"); %><% out.print(context.prepareWAPlacement("JSWebLibraries")); %>ApplicationChannelDetails.js<% out.print("</waplacement>"); %><% {out.flush();processLocalIncludeByServer((com.intershop.beehive.core.capi.request.ServletResponse)response,"inc/Modules", null, "5");} %><% {out.flush();processLocalIncludeByServer((com.intershop.beehive.core.capi.request.ServletResponse)response,"preview/Modules", null, "6");} %><% {Object temp_obj = (new Double(0)); getPipelineDictionary().put("level", temp_obj);} %><% _boolean_result=false;try {_boolean_result=((Boolean)(((!(context.getFormattedValue(getObject("ChannelApplicationBO:DisplayName"),null).equals(context.getFormattedValue("",null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",9,e);}if (_boolean_result) { %><% processOpenTag(response, pageContext, "breadcrumbtrail", new TagParameter[] {
new TagParameter("text1",context.getFormattedValue(" - ",null) + context.getFormattedValue(localizeText(context.getFormattedValue("IncChannelApplicationInformation.Details.text1",null)),null)),
new TagParameter("link",url(true,(new URLPipelineAction(context.getFormattedValue("ViewChannelMapApplication-Information",null))),(new URLParameterSet().addURLParameter(context.getFormattedValue("RepositoryUUID",null),context.getFormattedValue(getObject("Repository:UUID"),null))).addURLParameter(context.getFormattedValue("ApplicationID",null),context.getFormattedValue(getObject("ApplicationID"),null)))),
new TagParameter("text",getObject("ChannelApplicationBO:DisplayName"))}, 10); %><% } else { %><% processOpenTag(response, pageContext, "breadcrumbtrail", new TagParameter[] {
new TagParameter("text1",context.getFormattedValue(" - ",null) + context.getFormattedValue(localizeText(context.getFormattedValue("IncChannelApplicationInformation.Details.text1",null)),null)),
new TagParameter("link",url(true,(new URLPipelineAction(context.getFormattedValue("ViewChannelMapApplication-Information",null))),(new URLParameterSet().addURLParameter(context.getFormattedValue("RepositoryUUID",null),context.getFormattedValue(getObject("Repository:UUID"),null))).addURLParameter(context.getFormattedValue("ApplicationID",null),context.getFormattedValue(getObject("ApplicationID"),null)))),
new TagParameter("text",getObject("ChannelApplicationBO:ID"))}, 12); %><% } %><% {Object temp_obj = (getObject("ChannelApplicationBO:Extension(\"ManagementApplication\"):ManagementApplication")); getPipelineDictionary().put("ManagementApplicationBO", temp_obj);} %><% URLPipelineAction action3 = new URLPipelineAction(context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewApplicationSelect-Select",null)))),null));String site3 = null;String serverGroup3 = null;String actionValue3 = context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewApplicationSelect-Select",null)))),null);if (site3 == null){  site3 = action3.getDomain();  if (site3 == null)  {      site3 = com.intershop.beehive.core.capi.request.Request.getCurrent().getRequestSite().getDomainName();  }}if (serverGroup3 == null){  serverGroup3 = action3.getServerGroup();  if (serverGroup3 == null)  {      serverGroup3 = com.intershop.beehive.core.capi.request.Request.getCurrent().getRequestSite().getServerGroup();  }}out.print("<form");out.print(" method=\"");out.print("post");out.print("\"");out.print(" action=\"");out.print(context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewApplicationSelect-Select",null)))),null));out.print("\"");out.print(" name=\"");out.print("ChannelBrowserDetail");out.print("\"");out.print(">");out.print(context.prepareWACSRFTag(actionValue3, site3, serverGroup3,true)); %><table border="0" cellpadding="0" cellspacing="0" width="100%">
<tr>
<td class="table_title aldi"><% _boolean_result=false;try {_boolean_result=((Boolean)(((!(context.getFormattedValue(getObject("ChannelApplicationBO:DisplayName"),null).equals(context.getFormattedValue("",null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",19,e);}if (_boolean_result) { %><% {String value = null;try{value=context.getFormattedValue(getObject("ChannelApplicationBO:DisplayName"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {19}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %><% } else { %><% {String value = null;try{value=context.getFormattedValue(getObject("ChannelApplicationBO:ID"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {19}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %><% } %></td>
</tr>
</table>
<table border="0" cellpadding="0" cellspacing="0" width="100%">
<tr>
<td class="w e s">
<table border="0" cellpadding="0" cellspacing="0">
<tr><td colspan="2"><img src="<%=context.getFormattedValue(context.webRoot(),null)%>/images/space.gif" width="1" height="4" border="0" alt=""/></td></tr>
<tr>
<td nowrap="nowrap" class="label_text"><label class="label label_text"><% {out.write(localizeISText("IncChannelApplicationInformation.Type.label",null,null,null,null,null,null,null,null,null,null,null,null));} %>:&nbsp;</label></td>
<td class="table_detail"><% {out.write(localizeISText("IncChannelApplicationInformation.Application0.table_detail",null,null,encodeString(context.getFormattedValue(getObject("ChannelApplicationBO:ApplicationType:ID"),null)),null,null,null,null,null,null,null,null,null));} %></td>
</tr>
<tr>
<td nowrap="nowrap" class="label_text"><label class="label label_text"><% {out.write(localizeISText("IncChannelApplicationInformation.Created.label",null,null,null,null,null,null,null,null,null,null,null,null));} %>:&nbsp;</label></td>
<td class="table_detail"><% {String value = null;try{value=context.getFormattedValue(getObject("ChannelApplicationBO:PersistentObject:LastModified"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {33}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %></td>
</tr>
<tr>
<td nowrap="nowrap" class="label_text"><label class="label label_text"><% {out.write(localizeISText("IncChannelApplicationInformation.Storefront.label",null,null,null,null,null,null,null,null,null,null,null,null));} %>:&nbsp;</label></td>
<td class="table_detail"><% _boolean_result=false;try {_boolean_result=((Boolean)((((context.getFormattedValue(getObject("Repository:RepositoryDomain:Site:DefaultApplicationID"),null).equals(context.getFormattedValue(getObject("ChannelApplicationBO:ID"),null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",38,e);}if (_boolean_result) { %><% {Object temp_obj = ("-"); getPipelineDictionary().put("ApplicationUrlIdentifier", temp_obj);} %><% } else { %><% {Object temp_obj = (getObject("ChannelApplicationBO:UrlIdentifier")); getPipelineDictionary().put("ApplicationUrlIdentifier", temp_obj);} %><% } %><a href="<%=context.getFormattedValue(url(false,context.getFormattedValue("http",null), context.getFormattedValue("",null), (new URLPipelineAction(context.getFormattedValue("Default-Start",null),context.getFormattedValue("",null),context.getFormattedValue(getObject("ChannelApplicationBO:Site:DomainName"),null),context.getFormattedValue(getObject("ChannelApplicationBO:DefaultLocale:LocaleID"),null),context.getFormattedValue(getObject("ChannelApplicationBO:DefaultCurrency:Mnemonic"),null),context.getFormattedValue(getObject("ApplicationUrlIdentifier"),null)))),null)%>" class="form_link" target="_blank"><% {out.write(localizeISText("IncChannelApplicationInformation.Preview.link",null,null,null,null,null,null,null,null,null,null,null,null));} %></a>&nbsp;
<% _boolean_result=false;try {_boolean_result=((Boolean)(((((Boolean) (disableErrorMessages().isDefined(getObject("ApplicationPermissionMap:SLD_VIEW_STOREFRONT")))).booleanValue() && ((Boolean) ((((context.getFormattedValue(getObject("Repository:OwningDomain:DomainID"),null).equals(context.getFormattedValue(getObject("OrganizationDomain:DomainID"),null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",44,e);}if (_boolean_result) { %><% processOpenTag(response, pageContext, "previewlink", new TagParameter[] {
new TagParameter("linkTitle",localizeText(context.getFormattedValue("sld_enterprise_app.PreviewDesignView.linkTitle",null))),
new TagParameter("previewURL",url(true,(new URLPipelineAction(context.getFormattedValue("EditView-Start",null),context.getFormattedValue("",null),context.getFormattedValue("",null),context.getFormattedValue("",null),context.getFormattedValue("",null),context.getFormattedValue(getObject("ManagementApplicationBO:UrlIdentifier"),null))),(new URLParameterSet().addURLParameter(context.getFormattedValue("TargetSiteUUID",null),context.getFormattedValue(getObject("Repository:RepositoryDomain:Site:DomainID"),null))).addURLParameter(context.getFormattedValue("ContentRepositoryUUID",null),context.getFormattedValue(getObject("Repository:UUID"),null)).addURLParameter(context.getFormattedValue("ChannelID",null),context.getFormattedValue(getObject("Repository:UUID"),null)))),
new TagParameter("contextApplicationUUID",getObject("CurrentApplication:UUID")),
new TagParameter("contextPipeline","ViewChannelMapApplication-Information"),
new TagParameter("contextValue0",getObject("ApplicationID")),
new TagParameter("contextValue1",getObject("Repository:UUID")),
new TagParameter("linkText",localizeText(context.getFormattedValue("sld_enterprise_app.PreviewDesignView.linkText",null))),
new TagParameter("linkClass","form_link"),
new TagParameter("contextParameter0","ApplicationID"),
new TagParameter("contextParameter1","RepositoryUUID")}, 45); %><% } %></td>
</tr><% _boolean_result=false;try {_boolean_result=((Boolean)((((context.getFormattedValue(getObject("Repository:OwningDomain:UUID"),null).equals(context.getFormattedValue(getObject("CurrentOrganization:OrganizationDomain:UUID"),null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",57,e);}if (_boolean_result) { %><tr>
<td nowrap="nowrap" class="label_text"><label class="label label_text"><% {out.write(localizeISText("IncChannelApplicationInformation.Administrators.label",null,null,null,null,null,null,null,null,null,null,null,null));} %>:&nbsp;</label></td>
<td class="table_detail"><% _boolean_result=false;try {_boolean_result=((Boolean)((hasLoopElements("Users") ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",62,e);}if (_boolean_result) { %><% while (loop("Users","User","UserCounter")) { %><span class="<% _boolean_result=false;try {_boolean_result=((Boolean)((( ((Number) getObject("UserCounter")).doubleValue() >=((Number)(new Double(26))).doubleValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",64,e);}if (_boolean_result) { %>js-details-more<% } %>"><% _boolean_result=false;try {_boolean_result=((Boolean)((( ((Number) getObject("UserCounter")).doubleValue() >((Number)(new Double(1))).doubleValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",65,e);}if (_boolean_result) { %>, <% } %><% {String value = null;try{value=context.getFormattedValue(getObject("User:DataSheet:FirstName"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {66}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>&nbsp;<% {String value = null;try{value=context.getFormattedValue(getObject("User:DataSheet:LastName"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {66}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %></span><% } %><% _boolean_result=false;try {_boolean_result=((Boolean)((( ((Number) getObject("UserCounter")).doubleValue() >=((Number)(new Double(26))).doubleValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",69,e);}if (_boolean_result) { %><br /><a href="<%=context.getFormattedValue("#",null)%>" class="form_link js-link-showall"><% {out.write(localizeISText("IncChannelApplicationInformation.ShowAll",null,null,null,null,null,null,null,null,null,null,null,null));} %></a><a href="<%=context.getFormattedValue("#",null)%>" class="form_link js-link-showless"><% {out.write(localizeISText("IncChannelApplicationInformation.ShowLess",null,null,null,null,null,null,null,null,null,null,null,null));} %></a><% } %><% } %></td>
</tr><% } %><tr>
<td nowrap="nowrap" class="label_text"><label class="label label_text"><% {out.write(localizeISText("IncChannelApplicationInformation.Description.label",null,null,null,null,null,null,null,null,null,null,null,null));} %>:&nbsp;</label></td>
<td class="table_detail"><% {String value = null;try{value=context.getFormattedValue(getObject("ChannelApplicationBO:Description"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {79}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %></td>
</tr>
<tr><td colspan="2"><img src="<%=context.getFormattedValue(context.webRoot(),null)%>/images/space.gif" width="1" height="4" border="0" alt=""/></td></tr>
</table>
</td>
</tr><% _boolean_result=false;try {_boolean_result=((Boolean)(((((Boolean) ((((context.getFormattedValue(getObject("Repository:OwningDomain:UUID"),null).equals(context.getFormattedValue(getObject("CurrentOrganization:OrganizationDomain:UUID"),null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue() && !((Boolean) (getObject("ApplicationPermissionMap:isEmpty"))).booleanValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",85,e);}if (_boolean_result) { %><tr>
<td class="w e s">
<input type="hidden" name="RedirectedFromSite" value="<% {String value = null;try{value=context.getFormattedValue(getObject("Repository:Domain:DomainName"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {88}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>" />
<input type="hidden" name="RepositoryUUID" value="<%=context.getFormattedValue(getObject("Repository:UUID"),null)%>" />
<input type="hidden" name="ApplicationID" value="<%=context.getFormattedValue(getObject("ManagementApplicationBO:ID"),null)%>" />
<table border="0" cellspacing="4" cellpadding="0" >
<tr>
<td class="button"><input class="button" type="submit" name="applicationEdit" value="<%=context.getFormattedValue(localizeText(context.getFormattedValue("IncChannelApplicationInformation.ManageTheApplication.button",null)),null)%>" /></td>
</tr>
</table>
</td>
</tr><% } %></table><% out.print("</form>"); %><% _boolean_result=false;try {_boolean_result=((Boolean)(((!(context.getFormattedValue(getObject("ApplicationState:LastButOneBreadcrumb:Link"),null).equals(context.getFormattedValue("",null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",102,e);}if (_boolean_result) { %><% {out.flush();processLocalIncludeByServer((com.intershop.beehive.core.capi.request.ServletResponse)response,"inc/Back", null, "103");} %><% } else { %><div> 
<% URLPipelineAction action4 = new URLPipelineAction(context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewApplication-DisplayWelcomePage",null)))),null));String site4 = null;String serverGroup4 = null;String actionValue4 = context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewApplication-DisplayWelcomePage",null)))),null);if (site4 == null){  site4 = action4.getDomain();  if (site4 == null)  {      site4 = com.intershop.beehive.core.capi.request.Request.getCurrent().getRequestSite().getDomainName();  }}if (serverGroup4 == null){  serverGroup4 = action4.getServerGroup();  if (serverGroup4 == null)  {      serverGroup4 = com.intershop.beehive.core.capi.request.Request.getCurrent().getRequestSite().getServerGroup();  }}out.print("<form");out.print(" method=\"");out.print("post");out.print("\"");out.print(" action=\"");out.print(context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewApplication-DisplayWelcomePage",null)))),null));out.print("\"");out.print(" name=\"");out.print("backForm");out.print("\"");out.print(">");out.print(context.prepareWACSRFTag(actionValue4, site4, serverGroup4,true)); %><table border="0" cellspacing="0" cellpadding="0">
<tr>
<td class="backbar_left">
<table border="0" cellspacing="0" cellpadding="0">
<tr>
<td class="button">
<input class="button" type="submit" name="back" value="&lt;&lt;&nbsp;<%=context.getFormattedValue(localizeText(context.getFormattedValue("IncChannelApplicationInformation.Back.button",null)),null)%>"/>
</td>
</tr>
</table>
</td>
</tr>
</table><% out.print("</form>"); %></div><% } %><% printFooter(out); %>