<%@  page buffer="none" import="java.util.*,java.io.*,com.intershop.beehive.core.internal.template.*,com.intershop.beehive.core.internal.template.isml.*,com.intershop.beehive.core.capi.log.*,com.intershop.beehive.core.capi.resource.*,com.intershop.beehive.core.capi.util.UUIDMgr,com.intershop.beehive.core.capi.util.XMLHelper,com.intershop.beehive.foundation.util.*,com.intershop.beehive.core.internal.url.*,com.intershop.beehive.core.internal.resource.*,com.intershop.beehive.core.internal.wsrp.*,com.intershop.beehive.core.capi.pipeline.PipelineDictionary,com.intershop.beehive.core.capi.naming.NamingMgr,com.intershop.beehive.core.capi.pagecache.PageCacheMgr,com.intershop.beehive.core.capi.request.SessionMgr,com.intershop.beehive.core.internal.request.SessionMgrImpl,com.intershop.beehive.core.pipelet.PipelineConstants" extends="com.intershop.beehive.core.internal.template.AbstractTemplate" %><% 
boolean _boolean_result=false;
TemplateExecutionConfig context = getTemplateExecutionConfig();
createTemplatePageConfig(context.getServletRequest());
printHeader(out);
 %><% %><%@ page contentType="text/html;charset=utf-8" %><%setEncodingType("text/html"); %><% _boolean_result=false;try {_boolean_result=((Boolean)(((((Boolean) (disableErrorMessages().isDefined(getObject("Resource:ResourceOwner:Type")))).booleanValue() && ((Boolean) ((((context.getFormattedValue(getObject("Resource:ResourceOwner:Type"),null).equals(context.getFormattedValue("Instance Acquisition",null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",2,e);}if (_boolean_result) { %><div class="tooltip" style="display:none">
<table>
<tbody><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("Resource:LockCreationDate"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",6,e);}if (_boolean_result) { %><tr>
<td class="label"><% {out.write(localizeISText("LockOwnerToolTip.LockCreationDate.label",null,null,null,null,null,null,null,null,null,null,null,null));} %>:</td>
<td><% {String value = null;try{value=context.getFormattedValue(context.getFormattedValue(context.getFormattedValue(getObject("Resource:LockCreationDate"),new Integer(DATE_INPUT)),null) + context.getFormattedValue(" ",null) + context.getFormattedValue(context.getFormattedValue(getObject("Resource:LockCreationDate"),new Integer(DATE_TIME)),null),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {9}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %></td>
</tr><% } %> 
<% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("Resource:LockExpirationDate"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",12,e);}if (_boolean_result) { %><tr>
<td class="label"><% {out.write(localizeISText("LockOwnerToolTip.LockExpirationDate.label",null,null,null,null,null,null,null,null,null,null,null,null));} %>:</td>
<td><% {String value = null;try{value=context.getFormattedValue(context.getFormattedValue(context.getFormattedValue(getObject("Resource:LockExpirationDate"),new Integer(DATE_INPUT)),null) + context.getFormattedValue(" ",null) + context.getFormattedValue(context.getFormattedValue(getObject("Resource:LockExpirationDate"),new Integer(DATE_TIME)),null),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {15}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %></td>
</tr><% } %></tbody>
</table>
</div><% } else { %><div class="tooltip" style="display:none">
<table>
<tbody>
<tr>
<td class="label"><% {out.write(localizeISText("LockOwnerToolTip.OwningProcess.label",null,null,null,null,null,null,null,null,null,null,null,null));} %>:</td>
<td><% {String value = null;try{value=context.getFormattedValue(getObject("Resource:ResourceOwner:Name"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {27}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %></td>
</tr><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("Resource:ResourceOwner:Description"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",29,e);}if (_boolean_result) { %><tr>
<td class="label"><% {out.write(localizeISText("LockOwnerToolTip.ProcessDescription.label",null,null,null,null,null,null,null,null,null,null,null,null));} %>:</td>
<td><% {String value = null;try{value=context.getFormattedValue(getObject("Resource:ResourceOwner:Description"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {32}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %></td>
</tr><% } %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("Resource:ResourceOwner:User:Profile"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",35,e);}if (_boolean_result) { %><tr>
<td class="label"><% {out.write(localizeISText("LockOwnerToolTip.StartedBy.label",null,null,null,null,null,null,null,null,null,null,null,null));} %>:</td>
<td><% _boolean_result=false;try {_boolean_result=((Boolean)(((((Boolean) (disableErrorMessages().isDefined(getObject("CurrentUser")))).booleanValue() && ((Boolean) ((((context.getFormattedValue(getObject("Resource:ResourceOwner:User:ID"),null).equals(context.getFormattedValue(getObject("CurrentUser:ID"),null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",39,e);}if (_boolean_result) { %><% {out.write(localizeISText("LockOwnerToolTip.You",null,null,null,null,null,null,null,null,null,null,null,null));} %><% } else { %><% {String value = null;try{value=context.getFormattedValue(context.getFormattedValue(getObject("Resource:ResourceOwner:User:Profile:DataSheet:FirstName"),null) + context.getFormattedValue(" ",null) + context.getFormattedValue(getObject("Resource:ResourceOwner:User:Profile:DataSheet:LastName"),null) + context.getFormattedValue(" (",null) + context.getFormattedValue(getObject("Resource:ResourceOwner:User:Profile:Credentials:Login"),null) + context.getFormattedValue(")",null),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {42}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %><% } %></td>
</tr><% } %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("Resource:ResourceOwner:StartDate"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",47,e);}if (_boolean_result) { %><tr>
<td class="label"><% {out.write(localizeISText("ProductStatusDetail.StartDate.table_detail",null,null,null,null,null,null,null,null,null,null,null,null));} %></td>
<td><% {String value = null;try{value=context.getFormattedValue(context.getFormattedValue(context.getFormattedValue(getObject("Resource:ResourceOwner:StartDate"),new Integer(DATE_INPUT)),null) + context.getFormattedValue(" ",null) + context.getFormattedValue(context.getFormattedValue(getObject("Resource:ResourceOwner:StartDate"),new Integer(DATE_TIME)),null),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {50}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %></td>
</tr><% } %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("Resource:ResourceOwner:State"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",53,e);}if (_boolean_result) { %><tr>
<td class="label"><% {out.write(localizeISText("sld_enterprise_app.Status.label",null,null,null,null,null,null,null,null,null,null,null,null));} %>:</td>
<td><% {String value = null;try{value=context.getFormattedValue(getObject("Resource:ResourceOwner:State"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {56}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %></td>
</tr><% } %></tbody>
</table>
</div> 
<% } %><% printFooter(out); %>