<%@  page buffer="none" import="java.util.*,java.io.*,com.intershop.beehive.core.internal.template.*,com.intershop.beehive.core.internal.template.isml.*,com.intershop.beehive.core.capi.log.*,com.intershop.beehive.core.capi.resource.*,com.intershop.beehive.core.capi.util.UUIDMgr,com.intershop.beehive.core.capi.util.XMLHelper,com.intershop.beehive.foundation.util.*,com.intershop.beehive.core.internal.url.*,com.intershop.beehive.core.internal.resource.*,com.intershop.beehive.core.internal.wsrp.*,com.intershop.beehive.core.capi.pipeline.PipelineDictionary,com.intershop.beehive.core.capi.naming.NamingMgr,com.intershop.beehive.core.capi.pagecache.PageCacheMgr,com.intershop.beehive.core.capi.request.SessionMgr,com.intershop.beehive.core.internal.request.SessionMgrImpl,com.intershop.beehive.core.pipelet.PipelineConstants" extends="com.intershop.beehive.core.internal.template.AbstractTemplate" %><% 
boolean _boolean_result=false;
TemplateExecutionConfig context = getTemplateExecutionConfig();
createTemplatePageConfig(context.getServletRequest());
printHeader(out);
 %>
<% %><%@ page contentType="text/html;charset=utf-8" %><%setEncodingType("text/html"); %><table border="0" cellspacing="0" cellpadding="0" ><% {Object temp_obj = (getObject("paymenthistoryentry:LoggedData")); getPipelineDictionary().put("LoggedData", temp_obj);} %><% _boolean_result=false;try {_boolean_result=((Boolean)((hasLoopElements("LoggedData:Values") ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",7,e);}if (_boolean_result) { %><% while (loop("LoggedData:KeySet","AVKey",null)) { %><tr>
<td class="fielditem" width="150"><% {Object temp_obj = (localizeText(context.getFormattedValue(context.getFormattedValue(getObject("paymentservice:PaymentServiceID"),null) + context.getFormattedValue(".",null) + context.getFormattedValue(getObject("paymenthistoryentry:EventID"),null) + context.getFormattedValue(".",null) + context.getFormattedValue(getObject("AVKey"),null),null))); getPipelineDictionary().put("LocalizedAVKeyLabel", temp_obj);} %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("LocalizedAVKeyLabel"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",12,e);}if (_boolean_result) { %><% {String value = null;try{value=context.getFormattedValue(getObject("LocalizedAVKeyLabel"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {13}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>:
<% } else { %><% {String value = null;try{value=context.getFormattedValue(getObject("AVKey"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {15}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>:
<% } %></td>
<td class="table_detail"><% {Object temp_obj = (replace(context.getFormattedValue(getObject("LoggedData:get(AVKey)"),null),(String)("^\\{|\\}$"),(String)(""))); getPipelineDictionary().put("AVValue", temp_obj);} %><% {Object temp_obj = (localizeText(context.getFormattedValue(getObject("AVValue"),null))); getPipelineDictionary().put("LocalicedAVValueLabel", temp_obj);} %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("LocalicedAVValueLabel"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",22,e);}if (_boolean_result) { %><% {String value = null;try{value=context.getFormattedValue(getObject("LocalicedAVValueLabel"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {23}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %><% } else { %><% {String value = null;try{value=context.getFormattedValue(getObject("AVValue"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {25}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %><% } %>
&nbsp;
</td>
</tr><% } %><% } %><% {Object temp_obj = (getObject("paymenthistoryentry:LoggedData(CurrentRequest:Locale)")); getPipelineDictionary().put("LocalizedLoggedData", temp_obj);} %><% _boolean_result=false;try {_boolean_result=((Boolean)((hasLoopElements("LocalizedLoggedData:Values") ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",35,e);}if (_boolean_result) { %><% while (loop("LocalizedLoggedData:KeySet","AVKey",null)) { %><tr>
<td class="fielditem" width="150"><% {Object temp_obj = (localizeText(context.getFormattedValue(context.getFormattedValue(getObject("paymentservice:PaymentServiceID"),null) + context.getFormattedValue(".",null) + context.getFormattedValue(getObject("paymenthistoryentry:EventID"),null) + context.getFormattedValue(".",null) + context.getFormattedValue(getObject("AVKey"),null),null))); getPipelineDictionary().put("LocalizedAVKeyLabel", temp_obj);} %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("LocalizedAVKeyLabel"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",40,e);}if (_boolean_result) { %><% {String value = null;try{value=context.getFormattedValue(getObject("LocalizedAVKeyLabel"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {41}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>:
<% } else { %><% {String value = null;try{value=context.getFormattedValue(getObject("AVKey"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {43}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>:
<% } %></td>
<td class="table_detail"><% {String value = null;try{value=context.getFormattedValue(getObject("LocalizedLoggedData:get(AVKey)"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {47}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>&nbsp;
</td>
</tr><% } %><% } %></table><% printFooter(out); %>