<%@  page buffer="none" import="java.util.*,java.io.*,com.intershop.beehive.core.internal.template.*,com.intershop.beehive.core.internal.template.isml.*,com.intershop.beehive.core.capi.log.*,com.intershop.beehive.core.capi.resource.*,com.intershop.beehive.core.capi.util.UUIDMgr,com.intershop.beehive.core.capi.util.XMLHelper,com.intershop.beehive.foundation.util.*,com.intershop.beehive.core.internal.url.*,com.intershop.beehive.core.internal.resource.*,com.intershop.beehive.core.internal.wsrp.*,com.intershop.beehive.core.capi.pipeline.PipelineDictionary,com.intershop.beehive.core.capi.naming.NamingMgr,com.intershop.beehive.core.capi.pagecache.PageCacheMgr,com.intershop.beehive.core.capi.request.SessionMgr,com.intershop.beehive.core.internal.request.SessionMgrImpl,com.intershop.beehive.core.pipelet.PipelineConstants" extends="com.intershop.beehive.core.internal.template.AbstractTemplate" %><% 
boolean _boolean_result=false;
TemplateExecutionConfig context = getTemplateExecutionConfig();
createTemplatePageConfig(context.getServletRequest());
printHeader(out);
 %><% %><%@ page contentType="text/html;charset=utf-8" %><%response.setHeader(TemplateConstants.PERSONALIZED_HEADER, "1");setEncodingType("text/html"); %><% {out.flush();processLocalIncludeByServer((com.intershop.beehive.core.capi.request.ServletResponse)response,"modules/Modules", null, "2");} %><div class="modal-dialog">
<div class="modal-content">
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal" title="<% {out.write(localizeISText("dialog.close.text","",null,null,null,null,null,null,null,null,null,null,null));} %>" aria-label="<% {out.write(localizeISText("dialog.close.text","",null,null,null,null,null,null,null,null,null,null,null));} %>"><span aria-hidden="true">&times;</span></button>
<h2 class="modal-title"><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("ListItem"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",9,e);}if (_boolean_result) { %><% {String value = null;try{value=context.getFormattedValue(getObject("ListItem:Product:Name"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {10}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %><% } else { %><% {String value = null;try{value=context.getFormattedValue(getObject("ProductBO:Name"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {12}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %><% } %></h2>
</div><% _boolean_result=false;try {_boolean_result=((Boolean)(((((Boolean) (disableErrorMessages().isDefined(getObject("ERROR_ALERT_NOT_FOUND")))).booleanValue() || ((Boolean) (disableErrorMessages().isDefined(getObject("ERROR_ProductNotFound")))).booleanValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",17,e);}if (_boolean_result) { %><div class="modal-body"><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("ERROR_ALERT_NOT_FOUND"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",19,e);}if (_boolean_result) { %><div class="alert alert-danger" role="alert">
<p><% {out.write(localizeISText("account.productnotification.form.err_msg_alert_not_found","",null,null,null,null,null,null,null,null,null,null,null));} %></p>
</div><% } %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("ERROR_ProductNotFound"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",24,e);}if (_boolean_result) { %><div class="alert alert-danger" role="alert">
<p><% {out.write(localizeISText("account.productnotification.form.err_msg_invalid_product","",null,null,null,null,null,null,null,null,null,null,null));} %></p>
</div><% } %></div><% } else { %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("ListItem"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",33,e);}if (_boolean_result) { %><% URLPipelineAction action24 = new URLPipelineAction(context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewProductNotification-Dispatch",null))),(new URLParameterSet().addURLParameter(context.getFormattedValue("AjaxRequestMarker",null),context.getFormattedValue("true",null))).addURLParameter(context.getFormattedValue("SKU",null),context.getFormattedValue(getObject("ListItem:Product:ProductRef:ProductSKU"),null)).addURLParameter(context.getFormattedValue("CatalogCategoryID",null),context.getFormattedValue(getObject("CatalogCategoryID"),null))),null));String site24 = null;String serverGroup24 = null;String actionValue24 = context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewProductNotification-Dispatch",null))),(new URLParameterSet().addURLParameter(context.getFormattedValue("AjaxRequestMarker",null),context.getFormattedValue("true",null))).addURLParameter(context.getFormattedValue("SKU",null),context.getFormattedValue(getObject("ListItem:Product:ProductRef:ProductSKU"),null)).addURLParameter(context.getFormattedValue("CatalogCategoryID",null),context.getFormattedValue(getObject("CatalogCategoryID"),null))),null);if (site24 == null){  site24 = action24.getDomain();  if (site24 == null)  {      site24 = com.intershop.beehive.core.capi.request.Request.getCurrent().getRequestSite().getDomainName();  }}if (serverGroup24 == null){  serverGroup24 = action24.getServerGroup();  if (serverGroup24 == null)  {      serverGroup24 = com.intershop.beehive.core.capi.request.Request.getCurrent().getRequestSite().getServerGroup();  }}out.print("<form");out.print(" method=\"");out.print("post");out.print("\"");out.print(" action=\"");out.print(context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewProductNotification-Dispatch",null))),(new URLParameterSet().addURLParameter(context.getFormattedValue("AjaxRequestMarker",null),context.getFormattedValue("true",null))).addURLParameter(context.getFormattedValue("SKU",null),context.getFormattedValue(getObject("ListItem:Product:ProductRef:ProductSKU"),null)).addURLParameter(context.getFormattedValue("CatalogCategoryID",null),context.getFormattedValue(getObject("CatalogCategoryID"),null))),null));out.print("\"");out.print(" name=\"");out.print("AlertForm");out.print("\"");out.print(" data-hijax=\"");out.print("true");out.print("\"");out.print(" class=\"");out.print("form-horizontal bv-form");out.print("\"");out.print(">");out.print(context.prepareWACSRFTag(actionValue24, site24, serverGroup24,true)); %><div class="modal-body">
<input type="hidden" name="webform-id" value="AlertForm" />
<input type="hidden" name="AlertUUID" value="<% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("ListItem:UUID"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",40,e);}if (_boolean_result) { %><% {String value = null;try{value=context.getFormattedValue(getObject("ListItem:UUID"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {40}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %><% } %>" /><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("ERROR_PRICE"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",42,e);}if (_boolean_result) { %><div class="alert alert-danger" role="alert">
<p><% {out.write(localizeISText("account.productnotification.form.err_msg_invalid_price","",null,null,null,null,null,null,null,null,null,null,null));} %></p>
</div><% } %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("ERROR_EMailAddressInvalid"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",47,e);}if (_boolean_result) { %><div class="alert alert-danger" role="alert">
<p><% {out.write(localizeISText("account.productnotification.form.err_msg_invalid_email","",null,null,null,null,null,null,null,null,null,null,null));} %></p>
</div><% } %><div>
<img alt="<% {String value = null;try{value=context.getFormattedValue(getObject("ListItem:Product:Name"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {54}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>"
data-type="L" data-test="true" 
src="<% {String value = null;try{value=context.getFormattedValue(getObject("ProductBO:Extension(\"Image\"):ImageContainerBO:PrimaryImageBO(\"L\"):EffectiveUrl"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {56}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>">
</div>
<fieldset>
<div class="radio">
<label for="NoNotification">
<input type="radio" class="inputRadio" name="Alert_Type" value="NoNotification" id="NoNotification" /><% {out.write(localizeISText("account.productnotification.form.no_notification","",null,null,null,null,null,null,null,null,null,null,null));} %></label>
</div><% _boolean_result=false;try {_boolean_result=((Boolean)((((context.getFormattedValue(getObject("ListItem:HandlerClassName"),null).equals(context.getFormattedValue("com.intershop.component.mvc.capi.alert.StockConditionHandler",null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",67,e);}if (_boolean_result) { %><div class="radio">
<label for="InStockNotification">
<input type="radio" class="inputRadio" name="Alert_Type" value="InStockNotification" id="InStockNotification" checked="checked" /><% {out.write(localizeISText("account.productnotification.form.back_in_stock","",null,null,null,null,null,null,null,null,null,null,null));} %></label>
</div><% } %><% _boolean_result=false;try {_boolean_result=((Boolean)((((context.getFormattedValue(getObject("ListItem:HandlerClassName"),null).equals(context.getFormattedValue("com.intershop.component.mvc.capi.alert.PriceConditionHandler",null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",75,e);}if (_boolean_result) { %><div class="radio">
<label for="PriceNotification">
<input type="radio" class="inputRadio" name="Alert_Type" value="PriceNotification" id="PriceNotification" checked="checked" /><% {out.write(localizeISText("account.productnotification.form.price_drop_to","",null,null,null,null,null,null,null,null,null,null,null));} %></label>
</div><% } %></fieldset><% _boolean_result=false;try {_boolean_result=((Boolean)((((context.getFormattedValue(getObject("ListItem:HandlerClassName"),null).equals(context.getFormattedValue("com.intershop.component.mvc.capi.alert.PriceConditionHandler",null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",84,e);}if (_boolean_result) { %><div class="form-group">
<label class="col-sm-2 control-label" for="PriceValue" class="<% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("ERROR_PRICE"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",86,e);}if (_boolean_result) { %> inputError<% } %>"><% {out.write(localizeISText("account.productnotification.form.price","",null,null,null,null,null,null,null,null,null,null,null));} %></label>
<div class="col-sm-6 form-inline"><% while (loop("Currencies","currency",null)) { %><% _boolean_result=false;try {_boolean_result=((Boolean)((((context.getFormattedValue(getObject("currency:Mnemonic"),null).equals(context.getFormattedValue(getObject("ProductBO:Price:CurrencyMnemonic"),null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",89,e);}if (_boolean_result) { %><% {String value = null;try{value=context.getFormattedValue(getObject("currency:CurrencySymbol"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {90}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>&nbsp;
<% } %><% } %><input class="form-control" type="text" name="PriceValue" id="PriceValue" value="<% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("ListItem:Value"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",93,e);}if (_boolean_result) { %><% {String value = null;try{value=context.getFormattedValue(getObject("ListItem:Value"),new Integer(MONEY_SHORT),null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {93}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %><% } %>" /><% processOpenTag(response, pageContext, "productpriceadditionaltext", new TagParameter[] {
new TagParameter("ProductBO",getObject("ProductBO"))}, 94); %></div>
</div><% } %><div class="form-group">
<label class="col-sm-2 control-label" for="AlertForm_NotificationMailAddress"<% _boolean_result=false;try {_boolean_result=((Boolean)(((((Boolean) getObject("AlertForm:NotificationMailAddress:isMissing")).booleanValue() || ((Boolean) getObject("AlertForm:NotificationMailAddress:isInvalid")).booleanValue() || ((Boolean) (disableErrorMessages().isDefined(getObject("ERROR_EMailAddressInvalid")))).booleanValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",99,e);}if (_boolean_result) { %> class="inputError"<% } %>><% {out.write(localizeISText("account.productnotification.form.email","",null,null,null,null,null,null,null,null,null,null,null));} %></label>
<div class="col-sm-6">
<input class="form-control" type="text" name="AlertForm_NotificationMailAddress" id="AlertForm_NotificationMailAddress" value="<% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("AttributeValuesMap:NotificationMailAddress:StringValue"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",101,e);}if (_boolean_result) { %><% {String value = null;try{value=context.getFormattedValue(getObject("AttributeValuesMap:NotificationMailAddress:StringValue"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {101}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %><% } %>" />
</div>
</div>
</div>
<div class="modal-footer">
<input type="hidden" data-form-action="true"/>
<button type="submit" class="btn btn-primary" name="submitUpdate" value="Update"><% {out.write(localizeISText("account.productnotification.form.update","",null,null,null,null,null,null,null,null,null,null,null));} %></button>
<button type="button" class="btn btn-default" data-dismiss="modal" name="cancel"><% {out.write(localizeISText("account.productnotification.form.cancel","",null,null,null,null,null,null,null,null,null,null,null));} %></button>
</div><% out.print("</form>"); %><% } else { %><% URLPipelineAction action25 = new URLPipelineAction(context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewProductNotification-Dispatch",null))),(new URLParameterSet().addURLParameter(context.getFormattedValue("SKU",null),context.getFormattedValue(getObject("ProductBO:SKU"),null))).addURLParameter(context.getFormattedValue("CatalogCategoryID",null),context.getFormattedValue(getObject("CatalogCategoryID"),null))),null));String site25 = null;String serverGroup25 = null;String actionValue25 = context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewProductNotification-Dispatch",null))),(new URLParameterSet().addURLParameter(context.getFormattedValue("SKU",null),context.getFormattedValue(getObject("ProductBO:SKU"),null))).addURLParameter(context.getFormattedValue("CatalogCategoryID",null),context.getFormattedValue(getObject("CatalogCategoryID"),null))),null);if (site25 == null){  site25 = action25.getDomain();  if (site25 == null)  {      site25 = com.intershop.beehive.core.capi.request.Request.getCurrent().getRequestSite().getDomainName();  }}if (serverGroup25 == null){  serverGroup25 = action25.getServerGroup();  if (serverGroup25 == null)  {      serverGroup25 = com.intershop.beehive.core.capi.request.Request.getCurrent().getRequestSite().getServerGroup();  }}out.print("<form");out.print(" method=\"");out.print("post");out.print("\"");out.print(" action=\"");out.print(context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewProductNotification-Dispatch",null))),(new URLParameterSet().addURLParameter(context.getFormattedValue("SKU",null),context.getFormattedValue(getObject("ProductBO:SKU"),null))).addURLParameter(context.getFormattedValue("CatalogCategoryID",null),context.getFormattedValue(getObject("CatalogCategoryID"),null))),null));out.print("\"");out.print(" name=\"");out.print("AlertForm");out.print("\"");out.print(" data-hijax=\"");out.print("true");out.print("\"");out.print(" class=\"");out.print("form-horizontal bv-form");out.print("\"");out.print(">");out.print(context.prepareWACSRFTag(actionValue25, site25, serverGroup25,true)); %><div class="modal-body">
<input type="hidden" name="webform-id" value="AlertForm" /><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("ERROR_PRICE"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",122,e);}if (_boolean_result) { %><div class="alert alert-danger" role="alert">
<p><% {out.write(localizeISText("account.productnotification.form.err_msg_invalid_price","",null,null,null,null,null,null,null,null,null,null,null));} %></p>
</div><% } %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("ERROR_EMailAddressInvalid"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",127,e);}if (_boolean_result) { %><div class="alert alert-danger" role="alert">
<p><% {out.write(localizeISText("account.productnotification.form.err_msg_invalid_email","",null,null,null,null,null,null,null,null,null,null,null));} %></p>
</div><% } %><div>
<img alt="<% {String value = null;try{value=context.getFormattedValue(getObject("ProductBO:Name"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {134}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>" 
data-type="L" data-test="true" 
src="<% {String value = null;try{value=context.getFormattedValue(getObject("ProductBO:Extension(\"Image\"):ImageContainerBO:PrimaryImageBO(\"L\"):EffectiveUrl"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {136}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>">
</div>
<fieldset><% _boolean_result=false;try {_boolean_result=((Boolean)(((((Boolean) getObject("ProductBO:InventoryStatus:InStock")).booleanValue() && !((Boolean) getObject("ProductBO:isLastOrderDate")).booleanValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",140,e);}if (_boolean_result) { %><input type="hidden" name="Alert_Type" value="PriceNotification" id="PriceNotification"/>
<h4><% {out.write(localizeISText("account.productnotification.form.price_drop_to","",null,null,null,null,null,null,null,null,null,null,null));} %></h4>
<div class="form-group">
<label class="col-sm-2 control-label" for="PriceValue" class="<% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("ERROR_PRICE"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",145,e);}if (_boolean_result) { %> inputError<% } %>"><% {out.write(localizeISText("account.productnotification.form.price","",null,null,null,null,null,null,null,null,null,null,null));} %></label>
<div class="col-sm-6 form-inline"><% while (loop("Currencies","currency",null)) { %><% _boolean_result=false;try {_boolean_result=((Boolean)((((context.getFormattedValue(getObject("currency:Mnemonic"),null).equals(context.getFormattedValue(getObject("ProductBO:Price:CurrencyMnemonic"),null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",148,e);}if (_boolean_result) { %><% {String value = null;try{value=context.getFormattedValue(getObject("currency:CurrencySymbol"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {149}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>&nbsp;
<% } %><% } %><% processOpenTag(response, pageContext, "currentcustomerbo", new TagParameter[] {
new TagParameter("currentcustomerbo","CustomerBO")}, 153); %><% processOpenTag(response, pageContext, "currentuserbo", new TagParameter[] {
new TagParameter("currentuserbo","UserBO")}, 154); %><% processOpenTag(response, pageContext, "getproductpricecontext", new TagParameter[] {
new TagParameter("UserBO",getObject("UserBO")),
new TagParameter("CustomerBO",getObject("CustomerBO")),
new TagParameter("AddressSpecificPrice","true"),
new TagParameter("ProductPriceContext","ProductPriceContext")}, 155); %><% {Object temp_obj = (getObject("ProductBO:Extension(\"Pricing\")")); getPipelineDictionary().put("ProductPrice", temp_obj);} %><% {Object temp_obj = (getObject("ProductPrice:Price(\"SalePrice\",CurrentRequest:Currency,ProductPriceContext)")); getPipelineDictionary().put("SalePrice", temp_obj);} %><input class="form-control" type="text" name="PriceValue" id="PriceValue" value="<% _boolean_result=false;try {_boolean_result=((Boolean)(getObject("SalePrice:Range"))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",160,e);}if (_boolean_result) { %><% {String value = null;try{value=context.getFormattedValue(getObject("SalePrice:PriceRange:MinimumPrice"),new Integer(MONEY_SHORT),null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {160}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %><% } else {_boolean_result=false;try {_boolean_result=((Boolean)(getObject("SalePrice:Price:Available"))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",160,e);}if (_boolean_result) { %><% {String value = null;try{value=context.getFormattedValue(getObject("SalePrice:Price"),new Integer(MONEY_SHORT),null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {160}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %><% } else { %><% {String value = null;try{value=context.getFormattedValue(getObject("ProductBO:Price"),new Integer(MONEY_SHORT),null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {160}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %><% }} %>" /><% processOpenTag(response, pageContext, "productpriceadditionaltext", new TagParameter[] {
new TagParameter("ProductBO",getObject("ProductBO"))}, 161); %></div>
</div><% } else { %><input type="hidden" name="Alert_Type" value="InStockNotification" id="InStockNotification"/>
<p><% {out.write(localizeISText("account.productnotification.form.back_in_stock","",null,null,null,null,null,null,null,null,null,null,null));} %></p><% } %><div class="form-group">
<label class="col-sm-2 control-label" for="AlertForm_NotificationMailAddress"<% _boolean_result=false;try {_boolean_result=((Boolean)(((((Boolean) getObject("AlertForm:NotificationMailAddress:isMissing")).booleanValue() || ((Boolean) getObject("AlertForm:NotificationMailAddress:isInvalid")).booleanValue() || ((Boolean) (disableErrorMessages().isDefined(getObject("ERROR_EMailAddressInvalid")))).booleanValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",170,e);}if (_boolean_result) { %> class="inputError"<% } %>><% {out.write(localizeISText("account.productnotification.form.email","",null,null,null,null,null,null,null,null,null,null,null));} %></label>
<div class="col-sm-6">
<input class="form-control" type="text" name="AlertForm_NotificationMailAddress" id="AlertForm_NotificationMailAddress" value="<% _boolean_result=false;try {_boolean_result=((Boolean)((((Boolean) ((((context.getFormattedValue(getObject("CurrentUser:Profile:Email"),null).equals(context.getFormattedValue("",null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue() ? Boolean.FALSE : Boolean.TRUE) )).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",172,e);}if (_boolean_result) { %><% {String value = null;try{value=context.getFormattedValue(getObject("CurrentUser:Profile:Email"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {172}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %><% } else {_boolean_result=false;try {_boolean_result=((Boolean)((((Boolean) ((((context.getFormattedValue(getObject("CurrentUser:Profile:DefaultAddress:EMail"),null).equals(context.getFormattedValue("",null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue() ? Boolean.FALSE : Boolean.TRUE) )).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",172,e);}if (_boolean_result) { %><% {String value = null;try{value=context.getFormattedValue(getObject("CurrentUser:Profile:DefaultAddress:EMail"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {172}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %><% } else { %><% {String value = null;try{value=context.getFormattedValue(getObject("CurrentUser:Profile:Credentials:Login"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {172}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %><% }} %>" />
</div>
</div>
</fieldset>
</div>
<div class="modal-footer">
<input type="hidden" data-form-action="true"/>
<button type="submit" class="btn btn-primary" name="submitNew" value="Ok"><% {out.write(localizeISText("account.productnotification.form.ok","",null,null,null,null,null,null,null,null,null,null,null));} %></button>
<button type="button" class="btn btn-default" data-dismiss="modal" name="cancel"><% {out.write(localizeISText("account.productnotification.form.cancel","",null,null,null,null,null,null,null,null,null,null,null));} %></button>
</div><% out.print("</form>"); %><% } %><% } %></div>
</div><% printFooter(out); %>