<%@  page buffer="none" import="java.util.*,java.io.*,com.intershop.beehive.core.internal.template.*,com.intershop.beehive.core.internal.template.isml.*,com.intershop.beehive.core.capi.log.*,com.intershop.beehive.core.capi.resource.*,com.intershop.beehive.core.capi.util.UUIDMgr,com.intershop.beehive.core.capi.util.XMLHelper,com.intershop.beehive.foundation.util.*,com.intershop.beehive.core.internal.url.*,com.intershop.beehive.core.internal.resource.*,com.intershop.beehive.core.internal.wsrp.*,com.intershop.beehive.core.capi.pipeline.PipelineDictionary,com.intershop.beehive.core.capi.naming.NamingMgr,com.intershop.beehive.core.capi.pagecache.PageCacheMgr,com.intershop.beehive.core.capi.request.SessionMgr,com.intershop.beehive.core.internal.request.SessionMgrImpl,com.intershop.beehive.core.pipelet.PipelineConstants" extends="com.intershop.beehive.core.internal.template.AbstractTemplate" %><% 
boolean _boolean_result=false;
TemplateExecutionConfig context = getTemplateExecutionConfig();
createTemplatePageConfig(context.getServletRequest());
printHeader(out);
 %><% %><%@ page contentType="text/html;charset=utf-8" %><%setEncodingType("text/html"); %><table border="0" cellpadding="0" cellspacing="0" width="100%">
<tr>
<td><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("TargetCluster"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",6,e);}if (_boolean_result) { %><table cellpadding="0" cellspacing="0" border="0" width="100%" class="w e">
<tr>
<td class="table_header e s" width="70">&nbsp;</td>
<td class="table_header e s" nowrap="nowrap"><% {out.write(localizeISText("ChannelOutboundSyndicationTargetSystemConfiguration.TargetCluster.table_header",null,null,null,null,null,null,null,null,null,null,null,null));} %></td>
<td class="table_header e s" nowrap="nowrap"><% {out.write(localizeISText("ChannelOutboundSyndicationTargetSystemConfiguration.WebServerURL.table_header",null,null,null,null,null,null,null,null,null,null,null,null));} %></td>
<td class="table_header s" nowrap="nowrap"><% {out.write(localizeISText("ChannelOutboundSyndicationTargetSystemConfiguration.ServerGroup.table_header",null,null,null,null,null,null,null,null,null,null,null,null));} %></td>
</tr>
<tr> 
<td class="table_detail center e s" width="70"><input type="Radio" checked="checked" name="CreateProcess_TargetClusterID" value="<% {String value = null;try{value=context.getFormattedValue(getObject("TargetCluster:ClusterID"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {16}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>"/></td>
<td class="table_detail e s" nowrap="nowrap"><% while (loop("TargetCluster:TargetSystemsIterator","TargetSystem",null)) { %><% {String value = null;try{value=context.getFormattedValue(getObject("TargetSystem:Name"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {18}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %><% _boolean_result=false;try {_boolean_result=((Boolean)((hasNext("TargetSystem") ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",18,e);}if (_boolean_result) { %><br/><% } %><% } %>&nbsp;</td>
<td class="table_detail e s" nowrap="nowrap"><% while (loop("TargetCluster:TargetSystemsIterator","TargetSystem",null)) { %><% {String value = null;try{value=context.getFormattedValue(getObject("TargetSystem:WebServerURL"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {19}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %><% _boolean_result=false;try {_boolean_result=((Boolean)((hasNext("TargetSystem") ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",19,e);}if (_boolean_result) { %><br/><% } %><% } %>&nbsp;</td>
<td class="table_detail s" nowrap="nowrap"><% while (loop("TargetCluster:TargetSystemsIterator","TargetSystem",null)) { %><% {String value = null;try{value=context.getFormattedValue(getObject("TargetSystem:TargetServerGroup"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {20}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %><% _boolean_result=false;try {_boolean_result=((Boolean)((hasNext("TargetSystem") ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",20,e);}if (_boolean_result) { %><br/><% } %><% } %>&nbsp;</td>
</tr>
</table><% } else { %><table cellpadding="0" cellspacing="0" border="0" width="100%" class="w e">
<tr>
<td class="table_detail s"><% {out.write(localizeISText("ChannelOutboundSyndicationTargetSystemConfiguration.NoTargetClusterAvailable.table_detail",null,null,null,null,null,null,null,null,null,null,null,null));} %></td>
</tr>
</table><% } %></td>
</tr>
</table><% printFooter(out); %>