<%@  page buffer="none" import="java.util.*,java.io.*,com.intershop.beehive.core.internal.template.*,com.intershop.beehive.core.internal.template.isml.*,com.intershop.beehive.core.capi.log.*,com.intershop.beehive.core.capi.resource.*,com.intershop.beehive.core.capi.util.UUIDMgr,com.intershop.beehive.core.capi.util.XMLHelper,com.intershop.beehive.foundation.util.*,com.intershop.beehive.core.internal.url.*,com.intershop.beehive.core.internal.resource.*,com.intershop.beehive.core.internal.wsrp.*,com.intershop.beehive.core.capi.pipeline.PipelineDictionary,com.intershop.beehive.core.capi.naming.NamingMgr,com.intershop.beehive.core.capi.pagecache.PageCacheMgr,com.intershop.beehive.core.capi.request.SessionMgr,com.intershop.beehive.core.internal.request.SessionMgrImpl,com.intershop.beehive.core.pipelet.PipelineConstants" extends="com.intershop.beehive.core.internal.template.AbstractTemplate" %><% 
boolean _boolean_result=false;
TemplateExecutionConfig context = getTemplateExecutionConfig();
createTemplatePageConfig(context.getServletRequest());
printHeader(out);
 %><% %><%@ page contentType="text/html;charset=utf-8" %><%setEncodingType("text/html"); %><% {out.flush();processLocalIncludeByServer((com.intershop.beehive.core.capi.request.ServletResponse)response,"inc/ConfirmationScript", null, "2");} %><% out.print(context.prepareWAPlacement("JSWebLibraries")); %>bridge/bridge.js<% out.print("</waplacement>"); %><% out.print(context.prepareWAPlacement("JSWebLibraries")); %>AssignCategoriesDialogBehaviors.js<% out.print("</waplacement>"); %><table class="aldi" border="0" cellspacing="0" cellpadding="0" width="100%">
<tr>
<td width="100%" class="table_title2"><% _boolean_result=false;try {_boolean_result=((Boolean)(((!(context.getFormattedValue(getObject("HideAssignedCategories"),null).equals(context.getFormattedValue("true",null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",11,e);}if (_boolean_result) { %><a href="<%=context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewProduct_52-SetDisplayOptions",null))),(new URLParameterSet().addURLParameter(context.getFormattedValue("ChannelID",null),context.getFormattedValue(getObject("CurrentChannel:UUID"),null))).addURLParameter(context.getFormattedValue("DisplayVariable",null),context.getFormattedValue("HideAssignedCategories",null)).addURLParameter(context.getFormattedValue("DisplayValue",null),context.getFormattedValue("true",null)).addURLParameter(context.getFormattedValue("ProductID",null),context.getFormattedValue(getObject("Product:UUID"),null))),null)%>" class="table_opened"><% {out.write(localizeISText("ProductUpdateCategoriesSection_52.Categories.link",null,null,null,null,null,null,null,null,null,null,null,null));} %></a><% } else { %><a href="<%=context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewProduct_52-SetDisplayOptions",null))),(new URLParameterSet().addURLParameter(context.getFormattedValue("ChannelID",null),context.getFormattedValue(getObject("CurrentChannel:UUID"),null))).addURLParameter(context.getFormattedValue("DisplayVariable",null),context.getFormattedValue("HideAssignedCategories",null)).addURLParameter(context.getFormattedValue("DisplayValue",null),context.getFormattedValue("false",null)).addURLParameter(context.getFormattedValue("ProductID",null),context.getFormattedValue(getObject("Product:UUID"),null))),null)%>" class="table_closed"><% {out.write(localizeISText("ProductUpdateCategoriesSection_52.Categories.link",null,null,null,null,null,null,null,null,null,null,null,null));} %></a><% } %></td>
</tr><% _boolean_result=false;try {_boolean_result=((Boolean)(((!(context.getFormattedValue(getObject("HideAssignedCategories"),null).equals(context.getFormattedValue("true",null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",18,e);}if (_boolean_result) { %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("CurrentChannelPermissionMap:SLD_MANAGE_PRODUCTS"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",19,e);}if (_boolean_result) { %><!-- delete confirmation if one is selected--><% _boolean_result=false;try {_boolean_result=((Boolean)(((((Boolean) (disableErrorMessages().isDefined(getObject("confirmDeleteSection")))).booleanValue() && ((Boolean) ((hasLoopElements("PrefixIterator") ? Boolean.TRUE : Boolean.FALSE))).booleanValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",21,e);}if (_boolean_result) { %><tr>
<td><% URLPipelineAction action44 = new URLPipelineAction(context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewProductCategories_52-Dispatch",null)))),null));String site44 = null;String serverGroup44 = null;String actionValue44 = context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewProductCategories_52-Dispatch",null)))),null);if (site44 == null){  site44 = action44.getDomain();  if (site44 == null)  {      site44 = com.intershop.beehive.core.capi.request.Request.getCurrent().getRequestSite().getDomainName();  }}if (serverGroup44 == null){  serverGroup44 = action44.getServerGroup();  if (serverGroup44 == null)  {      serverGroup44 = com.intershop.beehive.core.capi.request.Request.getCurrent().getRequestSite().getServerGroup();  }}out.print("<form");out.print(" method=\"");out.print("post");out.print("\"");out.print(" action=\"");out.print(context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewProductCategories_52-Dispatch",null)))),null));out.print("\"");out.print(" name=\"");out.print("deleteConfirmation");out.print("\"");out.print(">");out.print(context.prepareWACSRFTag(actionValue44, site44, serverGroup44,true)); %><table border="0" cellspacing="0" cellpadding="0" width="100%"><% processOpenTag(response, pageContext, "messagebox", new TagParameter[] {
new TagParameter("parametername1","ChannelID"),
new TagParameter("parametervalue2",getObject("Product:UUID")),
new TagParameter("subject",localizeText(context.getFormattedValue("ProductUpdateCategoriesSection_52.ProductFromTheseCategories.subject",null))),
new TagParameter("cancelbtnname","cancelSection"),
new TagParameter("parametervalue1",getObject("ChannelID")),
new TagParameter("parametername2","ProductID"),
new TagParameter("prefixiterator",getObject("PrefixIterator")),
new TagParameter("prefix","CatalogCategoryID_"),
new TagParameter("okbtnname","deleteSection"),
new TagParameter("type","sdc"),
new TagParameter("class","n")}, 26); %></table><% out.print("</form>"); %></td>
</tr><% } %><!-- delete confirmation if nothing is selected--><% _boolean_result=false;try {_boolean_result=((Boolean)(((((Boolean) (disableErrorMessages().isDefined(getObject("confirmDeleteSection")))).booleanValue() && ((Boolean) ((((Boolean) ((hasLoopElements("PrefixIterator") ? Boolean.TRUE : Boolean.FALSE))).booleanValue() ? Boolean.FALSE : Boolean.TRUE) )).booleanValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",33,e);}if (_boolean_result) { %><tr>
<td><% URLPipelineAction action45 = new URLPipelineAction(context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewProductCategories_52-Dispatch",null)))),null));String site45 = null;String serverGroup45 = null;String actionValue45 = context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewProductCategories_52-Dispatch",null)))),null);if (site45 == null){  site45 = action45.getDomain();  if (site45 == null)  {      site45 = com.intershop.beehive.core.capi.request.Request.getCurrent().getRequestSite().getDomainName();  }}if (serverGroup45 == null){  serverGroup45 = action45.getServerGroup();  if (serverGroup45 == null)  {      serverGroup45 = com.intershop.beehive.core.capi.request.Request.getCurrent().getRequestSite().getServerGroup();  }}out.print("<form");out.print(" method=\"");out.print("post");out.print("\"");out.print(" action=\"");out.print(context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewProductCategories_52-Dispatch",null)))),null));out.print("\"");out.print(" name=\"");out.print("deleteCancelation");out.print("\"");out.print(">");out.print(context.prepareWACSRFTag(actionValue45, site45, serverGroup45,true)); %><table border="0" cellspacing="0" cellpadding="0" width="100%"><% processOpenTag(response, pageContext, "messagebox", new TagParameter[] {
new TagParameter("subject",localizeText(context.getFormattedValue("ProductUpdateCategoriesSection_52.Categorie.subject",null))),
new TagParameter("type","mde"),
new TagParameter("class","n")}, 38); %></table><% out.print("</form>"); %></td>
</tr><% } %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("RunningAuctionCounter"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",46,e);}if (_boolean_result) { %><% _boolean_result=false;try {_boolean_result=((Boolean)(((((Boolean) ((disableErrorMessages().isDefined(getObject("Product:RunningAuctions"))))).booleanValue() && ((Boolean) ((( ((Number) getObject("Product:RunningAuctions")).doubleValue() >((Number)(new Double(0))).doubleValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",47,e);}if (_boolean_result) { %><tr>
<td>
<table border="0" cellspacing="0" cellpadding="4" width="100%" class="error_box w e s">
<tr valign="top">
<td class="error_icon top e"><img src="<%=context.getFormattedValue(context.webRoot(),null)%>/images/error.gif" width="16" height="15" alt="" border="0"/></td><% _boolean_result=false;try {_boolean_result=((Boolean)((( ((Number) getObject("Product:RunningAuctions")).doubleValue() ==((Number)(new Double(1))).doubleValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",53,e);}if (_boolean_result) { %><td class="error top" width="100%"><b><% {out.write(localizeISText("ProductUpdateCategoriesSection_52.WarningThisProductIsCurrentlyPartOfAnAuction.error",null,null,null,null,null,null,null,null,null,null,null,null));} %></b><br/><% } else { %><td class="error top" width="100%"><b><% {out.write(localizeISText("ProductUpdateCategoriesSection_52.WarningThisProductIsCurrentlyPartOfXAuctions.error",null,null,context.getFormattedValue(getObject("Product:RunningAuctions"),null),null,null,null,null,null,null,null,null,null));} %></b><br/><% } %><% {out.write(localizeISText("ProductUpdateCategoriesSection_52.PleaseContactYourAuctionManagerBeforeEditing.error",null,null,null,null,null,null,null,null,null,null,null,null));} %></td>
</tr>
</table>
</td>
</tr><% } %><% } %><% } %><tr>
<td class="table_title_description n"><% {out.write(localizeISText("ProductUpdateCategoriesSection_52.TheListShowsAllCategoriesThatContainThisProduct.table_title_description",null,null,context.getFormattedValue("<img src=\"",null) + context.getFormattedValue(context.webRoot(),null) + context.getFormattedValue("/images/status_implicitly_bound.gif\" alt=\"",null) + context.getFormattedValue(localizeText(context.getFormattedValue("ProductUpdateCategoriesSection_52.DynamicProductBinding.alt",null)),null) + context.getFormattedValue("\" title=\"",null) + context.getFormattedValue(localizeText(context.getFormattedValue("ProductUpdateCategoriesSection_52.DynamicProductBinding.title",null)),null) + context.getFormattedValue("\" border=\"0\"/>",null),null,null,null,null,null,null,null,null,null));} %></td>
</tr><% } %></table><% _boolean_result=false;try {_boolean_result=((Boolean)(((!(context.getFormattedValue(getObject("HideAssignedCategories"),null).equals(context.getFormattedValue("true",null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",78,e);}if (_boolean_result) { %><% URLPipelineAction action46 = new URLPipelineAction(context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewProductCategories_52-Dispatch",null)))),null));String site46 = null;String serverGroup46 = null;String actionValue46 = context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewProductCategories_52-Dispatch",null)))),null);if (site46 == null){  site46 = action46.getDomain();  if (site46 == null)  {      site46 = com.intershop.beehive.core.capi.request.Request.getCurrent().getRequestSite().getDomainName();  }}if (serverGroup46 == null){  serverGroup46 = action46.getServerGroup();  if (serverGroup46 == null)  {      serverGroup46 = com.intershop.beehive.core.capi.request.Request.getCurrent().getRequestSite().getServerGroup();  }}out.print("<form");out.print(" method=\"");out.print("post");out.print("\"");out.print(" action=\"");out.print(context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewProductCategories_52-Dispatch",null)))),null));out.print("\"");out.print(" name=\"");out.print("assignedCategoriesForm");out.print("\"");out.print(">");out.print(context.prepareWACSRFTag(actionValue46, site46, serverGroup46,true)); %><% _boolean_result=false;try {_boolean_result=((Boolean)((hasLoopElements("CatalogCategories") ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",80,e);}if (_boolean_result) { %><table width="100%" border="0" cellspacing="0" cellpadding="0" id="asyncCategoryAssignmentBlock">
<tr><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("CurrentChannelPermissionMap:SLD_MANAGE_PRODUCTS"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",83,e);}if (_boolean_result) { %><td class="table_header center w e s" nowrap="nowrap" width="80">
<div id="CategoryAssignments-A">
<table border="0" cellspacing="0" cellpadding="0" class="table_header center" width="100%">
<tr>
<td nowrap="nowrap">
<a href="javascript:selectAll('assignedCategoriesForm','CatalogCategoryID','CategoryAssignments-A','CategoryAssignments-B');" class="tableheader"><% {out.write(localizeISText("ProductUpdateCategoriesSection_52.SelectAll.link",null,null,null,null,null,null,null,null,null,null,null,null));} %></a>
</td>
</tr>
</table>
</div>
<div id="CategoryAssignments-B" style="display:none">
<table border="0" cellspacing="0" cellpadding="0" class="table_header center" width="100%">
<tr>
<td nowrap="nowrap">
<a href="javascript:selectAll('assignedCategoriesForm','CatalogCategoryID','CategoryAssignments-A','CategoryAssignments-B');" class="tableheader"><% {out.write(localizeISText("ProductUpdateCategoriesSection_52.ClearAll.link",null,null,null,null,null,null,null,null,null,null,null,null));} %></a>
</td>
</tr>
</table>
</div>
</td>
<td class="table_header e s" width="60%"><% {out.write(localizeISText("ProductUpdateCategoriesSection_52.Category.table_header",null,null,null,null,null,null,null,null,null,null,null,null));} %></td><% } else { %><td class="table_header e w s" width="60%"><% {out.write(localizeISText("ProductUpdateCategoriesSection_52.Category.table_header",null,null,null,null,null,null,null,null,null,null,null,null));} %></td><% } %><td class="table_header e s" width="20%"><% {out.write(localizeISText("ProductUpdateCategoriesSection_52.CategoryID.table_header",null,null,null,null,null,null,null,null,null,null,null,null));} %></td>
<td class="table_header e s" nowrap="nowrap"><% {out.write(localizeISText("ProductUpdateCategoriesSection_52.DefaultCategory.table_header",null,null,null,null,null,null,null,null,null,null,null,null));} %></td>
</tr><% while (loop("CatalogCategories","list",null)) { %><!-- Checks if the sub-category has dynamic product binding (SQD in the current channel domain) --><% processOpenTag(response, pageContext, "createmap", new TagParameter[] {
new TagParameter("key0","Name"),
new TagParameter("value0",getObject("list:SearchQueryDefinitionName")),
new TagParameter("mapname","GetSQDByNameParamMap")}, 113); %><% {try{executePipeline("ProcessSearchQueryDefinitionBySearchIndex-GetCategorySQDByName",((java.util.Map)(getObject("GetSQDByNameParamMap"))),"GetSQDByNameResultDict");}catch(Exception e){Logger.error(this,"ISPIPELINE failed. Line: 114.",e);}} %><tr><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("CurrentChannelPermissionMap:SLD_MANAGE_PRODUCTS"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",119,e);}if (_boolean_result) { %><td class="w e s center">
<input type="checkbox" name="CatalogCategoryID_<%=context.getFormattedValue(getObject("list:UUID"),null)%>" value="<%=context.getFormattedValue(getObject("list:UUID"),null)%>" <% _boolean_result=false;try {_boolean_result=((Boolean)(((((Boolean) (hasLoopElements("PrefixIterator") ? Boolean.TRUE : Boolean.FALSE)).booleanValue() && !((Boolean) ((disableErrorMessages().isDefined(getObject("GetSQDByNameResultDict:SearchQueryDefinition"))))).booleanValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",121,e);}if (_boolean_result) { %><% while (loop("PrefixIterator","Selected",null)) { %><% _boolean_result=false;try {_boolean_result=((Boolean)((((context.getFormattedValue(getObject("Selected"),null).equals(context.getFormattedValue(getObject("list:UUID"),null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",121,e);}if (_boolean_result) { %>checked="checked"<% if (getLoopStack().isEmpty()) {Logger.error(this,"ISBREAK occured outside ISLOOP. Line: {}",121);}else{getLoopStack().pop();break;} %><% } %><% } %><% } %> <% _boolean_result=false;try {_boolean_result=((Boolean)(((((Boolean) (disableErrorMessages().isDefined(getObject("GetSQDByNameResultDict:SearchQueryDefinition")))).booleanValue() || ((Boolean) (((((Boolean) getObject("Product:DerivedProduct")).booleanValue() && ((Boolean) (((!(context.getFormattedValue(getObject("Product:DomainID"),null).equals(context.getFormattedValue(getObject("list:ProductCategoryAssignment(Product):DomainID"),null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",121,e);}if (_boolean_result) { %>disabled="disabled"<% } %>/>
</td><% } %><td class="table_detail e s <% _boolean_result=false;try {_boolean_result=((Boolean)((((Boolean) (disableErrorMessages().isDefined(getObject("CurrentChannelPermissionMap:SLD_MANAGE_PRODUCTS")))).booleanValue() ? Boolean.FALSE : Boolean.TRUE) )).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",124,e);}if (_boolean_result) { %>w<% } %>"><% while (loop("CategoryPath:get(list:UUID)","parent_path",null)) { %><% _boolean_result=false;try {_boolean_result=((Boolean)((((context.getFormattedValue(getObject("parent_path:Name"),null).equals(context.getFormattedValue(getObject("list:Name"),null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",126,e);}if (_boolean_result) { %><% _boolean_result=false;try {_boolean_result=((Boolean)(((((Boolean) (disableErrorMessages().isDefined(getObject("CurrentChannelPermissionMap:SLD_MANAGE_PRODUCTS")))).booleanValue() || ((Boolean) (disableErrorMessages().isDefined(getObject("CurrentChannelPermissionMap:SLD_VIEW_CATALOGS")))).booleanValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",127,e);}if (_boolean_result) { %><a href="<%=context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewProductCategoryAssignmentWizard_52-CategoryDetails",null))),(new URLParameterSet().addURLParameter(context.getFormattedValue("CategoryUUID",null),context.getFormattedValue(getObject("list:UUID"),null))).addURLParameter(context.getFormattedValue("ProductID",null),context.getFormattedValue(getObject("Product:UUID"),null)).addURLParameter(context.getFormattedValue("cameFrom",null),context.getFormattedValue("productCategoriesList",null)).addURLParameter(context.getFormattedValue("ChannelID",null),context.getFormattedValue(getObject("ChannelID"),null))),null)%>" class="table_detail_link"><b><% {String value = null;try{value=context.getFormattedValue(getObject("list:DisplayName"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {128}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %></b></a>&nbsp;
<% _boolean_result=false;try {_boolean_result=((Boolean)(getObject("list:isHotDealsCategory"))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",129,e);}if (_boolean_result) { %><a href="<%=context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewProductCategoryAssignmentWizard_52-CategoryDetails",null))),(new URLParameterSet().addURLParameter(context.getFormattedValue("CategoryUUID",null),context.getFormattedValue(getObject("list:HotDealsCategory:UUID"),null))).addURLParameter(context.getFormattedValue("ProductID",null),context.getFormattedValue(getObject("Product:UUID"),null)).addURLParameter(context.getFormattedValue("cameFrom",null),context.getFormattedValue("productCategoriesList",null)).addURLParameter(context.getFormattedValue("ChannelID",null),context.getFormattedValue(getObject("ChannelID"),null))),null)%>" class="table_detail_link">
<b><% {out.write(localizeISText("ProductUpdateCategoriesSection_52.HotDealsCategoryOf.link",null,null,encodeString(context.getFormattedValue(getObject("list:HotDealsOwner:DisplayName"),null)),null,null,null,null,null,null,null,null,null));} %></b></a><% } %><% } else { %><a href="#" class="table_detail_link"><b><% {String value = null;try{value=context.getFormattedValue(getObject("list:DisplayName"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {134}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %></b></a>&nbsp;
<% _boolean_result=false;try {_boolean_result=((Boolean)(getObject("list:isHotDealsCategory"))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",135,e);}if (_boolean_result) { %><a href="#" class="table_detail_link">
<b><% {out.write(localizeISText("ProductUpdateCategoriesSection_52.HotDealsCategoryOf.link",null,null,encodeString(context.getFormattedValue(getObject("list:HotDealsOwner:DisplayName"),null)),null,null,null,null,null,null,null,null,null));} %></b></a><% } %><% } %><% } else { %><% {String value = null;try{value=context.getFormattedValue(getObject("parent_path:DisplayName"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {140}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>&nbsp;&gt;&nbsp;
<% } %><% } %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("GetSQDByNameResultDict:SearchQueryDefinition"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",143,e);}if (_boolean_result) { %><img src="<%=context.getFormattedValue(context.webRoot(),null)%>/images/status_implicitly_bound.gif" alt="<%=context.getFormattedValue(localizeText(context.getFormattedValue("ProductUpdateCategoriesSection_52.DynamicProductBinding.alt",null)),null)%>" title="<%=context.getFormattedValue(localizeText(context.getFormattedValue("ProductUpdateCategoriesSection_52.DynamicProductBinding.title",null)),null)%>" border="0"/><% } %></td>
<td class="table_detail e s"><% _boolean_result=false;try {_boolean_result=((Boolean)(((((Boolean) (disableErrorMessages().isDefined(getObject("CurrentChannelPermissionMap:SLD_MANAGE_PRODUCTS")))).booleanValue() || ((Boolean) (disableErrorMessages().isDefined(getObject("CurrentChannelPermissionMap:SLD_VIEW_CATALOGS")))).booleanValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",146,e);}if (_boolean_result) { %><a href="<%=context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewProductCategoryAssignmentWizard_52-CategoryDetails",null))),(new URLParameterSet().addURLParameter(context.getFormattedValue("CategoryUUID",null),context.getFormattedValue(getObject("list:UUID"),null))).addURLParameter(context.getFormattedValue("ProductID",null),context.getFormattedValue(getObject("Product:UUID"),null)).addURLParameter(context.getFormattedValue("cameFrom",null),context.getFormattedValue("productCategoriesList",null)).addURLParameter(context.getFormattedValue("ChannelID",null),context.getFormattedValue(getObject("ChannelID"),null))),null)%>" class="table_detail_link"><b><% {String value = null;try{value=context.getFormattedValue(getObject("list:Name"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {147}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %></b></a>&nbsp;
<% } else { %><a href="#" class="table_detail_link"><b><% {String value = null;try{value=context.getFormattedValue(getObject("list:Name"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {149}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %></b></a>&nbsp;
<% } %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("GetSQDByNameResultDict:SearchQueryDefinition"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",151,e);}if (_boolean_result) { %><img src="<%=context.getFormattedValue(context.webRoot(),null)%>/images/status_implicitly_bound.gif" alt="<%=context.getFormattedValue(localizeText(context.getFormattedValue("ProductUpdateCategoriesSection_52.DynamicProductBinding.alt",null)),null)%>" title="<%=context.getFormattedValue(localizeText(context.getFormattedValue("ProductUpdateCategoriesSection_52.DynamicProductBinding.title",null)),null)%>" border="0"/><% } %></td>
<td class="table_detail e s center"><% _boolean_result=false;try {_boolean_result=((Boolean)((((context.getFormattedValue(getObject("Product:DefaultCatalogCategory:UUID"),null).equals(context.getFormattedValue(getObject("list:UUID"),null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",154,e);}if (_boolean_result) { %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("CurrentChannelPermissionMap:SLD_MANAGE_PRODUCTS"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",155,e);}if (_boolean_result) { %><input type="radio" name="defaultCategory" value="<% {String value = null;try{value=context.getFormattedValue(getObject("list:UUID"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {156}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>" checked="checked"/><% } else { %><input type="radio" name="defaultCategory" value="<% {String value = null;try{value=context.getFormattedValue(getObject("list:UUID"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {158}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>" checked="checked" disabled="disabled"/><% } %><% } else { %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("CurrentChannelPermissionMap:SLD_MANAGE_PRODUCTS"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",161,e);}if (_boolean_result) { %><input type="radio" name="defaultCategory" value="<% {String value = null;try{value=context.getFormattedValue(getObject("list:UUID"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {162}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>" /><% } else { %><input type="radio" name="defaultCategory" value="<% {String value = null;try{value=context.getFormattedValue(getObject("list:UUID"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {164}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>" disabled="disabled"/><% } %><% } %></td>
</tr><% } %><tr>
<td width="100%" colspan="5"><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("CurrentChannelPermissionMap:SLD_MANAGE_PRODUCTS"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",172,e);}if (_boolean_result) { %><table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr>
<td class="w e s" align="right">
<table border="0" cellspacing="4" cellpadding="0">
<tr><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("ProductLockedForMe"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",178,e);}if (_boolean_result) { %><td class="button">
<input type="button" class="button" name="ManageCategories" value="<%=context.getFormattedValue(localizeText(context.getFormattedValue("ProductUpdateCategoriesSection_52.Assign.button",null)),null)%>" />
</td><% } else { %><td class="button">
<input type="button" class="button" name="ManageCategories" value="<%=context.getFormattedValue(localizeText(context.getFormattedValue("ProductUpdateCategoriesSection_52.Assign.button",null)),null)%>" disabled="disabled"/>
</td><% } %><% _boolean_result=false;try {_boolean_result=((Boolean)((hasLoopElements("CatalogCategories") ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",187,e);}if (_boolean_result) { %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("ProductLockedForMe"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",188,e);}if (_boolean_result) { %><td class="button">
<input type="hidden" name="ChannelID" value="<% {String value = null;try{value=context.getFormattedValue(getObject("ChannelID"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {190}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>"/>
<input type="hidden" name="OnlyOneProduct" value="true"/>
<input type="hidden" name="ProductID" value="<% {String value = null;try{value=context.getFormattedValue(getObject("Product:UUID"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {192}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>"/>
<input type="hidden" name="ProductID_<% {String value = null;try{value=context.getFormattedValue(getObject("Product:UUID"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {193}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>" value="<% {String value = null;try{value=context.getFormattedValue(getObject("Product:UUID"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {193}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>"/>
<input type="submit" name="applySection" value="<%=context.getFormattedValue(localizeText(context.getFormattedValue("ProductUpdateCategoriesSection_52.Apply.button",null)),null)%>" class="button"/>
</td>
<td class="button">
<input type="submit" name="confirmDeleteSection" value="<%=context.getFormattedValue(localizeText(context.getFormattedValue("ProductUpdateCategoriesSection_52.Delete.button",null)),null)%>" class="button"/>
</td><% } else { %><td class="button">
<input type="submit" name="applySection" value="<%=context.getFormattedValue(localizeText(context.getFormattedValue("ProductUpdateCategoriesSection_52.Apply.button",null)),null)%>" class="button" disabled="disabled"/>
</td>
<td class="button">
<input type="submit" name="confirmDeleteSection" value="<%=context.getFormattedValue(localizeText(context.getFormattedValue("ProductUpdateCategoriesSection_52.Delete.button",null)),null)%>" class="button" disabled="disabled"/>
</td><% } %><% } %></tr>
</table>
</td>
</tr>
</table><% } %></td>
</tr>
</table><% } else { %> 
<table width="100%" border="0" cellspacing="0" cellpadding="0" id="asyncCategoryAssignmentBlock">
<tr>
<td colspan="3" class="table_detail w e s"><% {out.write(localizeISText("ProductUpdateCategoriesSection_52.ThisProductIsNotAssignedToAnyCategories.table_detail",null,null,null,null,null,null,null,null,null,null,null,null));} %></td>
</tr>
<tr>
<td width="100%" colspan="5"><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("CurrentChannelPermissionMap:SLD_MANAGE_PRODUCTS"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",226,e);}if (_boolean_result) { %><table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr>
<td class="w e s" align="right">
<table border="0" cellspacing="4" cellpadding="0">
<tr><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("ProductLockedForMe"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",232,e);}if (_boolean_result) { %><td class="button">
<input type="hidden" name="ChannelID" value="<% {String value = null;try{value=context.getFormattedValue(getObject("ChannelID"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {234}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>"/>
<input type="hidden" name="OnlyOneProduct" value="true"/>
<input type="hidden" name="ProductID" value="<% {String value = null;try{value=context.getFormattedValue(getObject("Product:UUID"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {236}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>"/>
<input type="hidden" name="ProductID_<% {String value = null;try{value=context.getFormattedValue(getObject("Product:UUID"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {237}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>" value="<% {String value = null;try{value=context.getFormattedValue(getObject("Product:UUID"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {237}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>"/>
<input type="button" class="button" name="ManageCategories" value="<%=context.getFormattedValue(localizeText(context.getFormattedValue("ProductUpdateCategoriesSection_52.Assign.button",null)),null)%>" />
</td><% } else { %><td class="button">
<input type="button" class="button" name="ManageCategories" value="<%=context.getFormattedValue(localizeText(context.getFormattedValue("ProductUpdateCategoriesSection_52.Assign.button",null)),null)%>" disabled="disabled"/>
</td><% } %></tr>
</table>
</td>
</tr>
</table><% } %></td>
</tr>
</table><% } %><% out.print("</form>"); %><% } %><% {Object temp_obj = (context.getFormattedValue("catalogTree_",null) + context.getFormattedValue(getObject("CurrentChannel:Id"),null)); getPipelineDictionary().put("TreeId", temp_obj);} %><div id="CategoriesMgmtDialog" class="js-dialog" width="730" height="478" data-title="Select Categories">
<iframe src="<%=context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewProduct_52-GetDynamicCategoriesData",null))),(new URLParameterSet().addURLParameter(context.getFormattedValue("ProductID",null),context.getFormattedValue(getObject("ProductID"),null)))),null)%>" class="dialog-iframe" name="CategoriesMgmtDialog"></iframe>
</div>
<script type="text/javascript">
assignCategories('<%=context.getFormattedValue("#",null)%>CategoriesMgmtDialog', 'input[name="ManageCategories"]');
</script><% printFooter(out); %>