<%@  page buffer="none" import="java.util.*,java.io.*,com.intershop.beehive.core.internal.template.*,com.intershop.beehive.core.internal.template.isml.*,com.intershop.beehive.core.capi.log.*,com.intershop.beehive.core.capi.resource.*,com.intershop.beehive.core.capi.util.UUIDMgr,com.intershop.beehive.core.capi.util.XMLHelper,com.intershop.beehive.foundation.util.*,com.intershop.beehive.core.internal.url.*,com.intershop.beehive.core.internal.resource.*,com.intershop.beehive.core.internal.wsrp.*,com.intershop.beehive.core.capi.pipeline.PipelineDictionary,com.intershop.beehive.core.capi.naming.NamingMgr,com.intershop.beehive.core.capi.pagecache.PageCacheMgr,com.intershop.beehive.core.capi.request.SessionMgr,com.intershop.beehive.core.internal.request.SessionMgrImpl,com.intershop.beehive.core.pipelet.PipelineConstants" extends="com.intershop.beehive.core.internal.template.AbstractTemplate" %><% 
boolean _boolean_result=false;
TemplateExecutionConfig context = getTemplateExecutionConfig();
createTemplatePageConfig(context.getServletRequest());
printHeader(out);
 %>

<%@page import="com.intershop.component.foundation.capi.clipboard.Clipboard"%>
<% %><%@ page contentType="text/html;charset=utf-8" %><%setEncodingType("text/html"); %><table cellpadding="0" cellspacing="0" border="0" width="100%" class="editbox aldi" ><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("EditConditionTypeGroup"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",18,e);}if (_boolean_result) { %><input type="hidden" name="TargetConditionID" value="<% {String value = null;try{value=context.getFormattedValue(getObject("EditConditionTypeGroup:UUID"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {19}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>"/><% } else {_boolean_result=false;try {_boolean_result=((Boolean)(((((Boolean) (disableErrorMessages().isDefined(getObject("TargetConditionID")))).booleanValue() && ((Boolean) ((( ((Number) (new Double(context.getFormattedValue((context.getFormattedValue(getObject("TargetConditionID"),null).trim()),null).length()))).doubleValue() >((Number)(new Double(0))).doubleValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",20,e);}if (_boolean_result) { %><input type="hidden" name="TargetConditionID" value="<% {String value = null;try{value=context.getFormattedValue(getObject("TargetConditionID"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {21}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>"/><% }} %><tr>
<td class="fielditem2"><% {out.write(localizeISText("ConditionEditor.New.subject",null,null,null,null,null,null,null,null,null,null,null,null));} %> <% {String value = null;try{value=context.getFormattedValue(getObject("ConditionTypesMap:get(NewConditionForm:ConditionType:Value)"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {26}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %> <% {out.write(localizeISText("ConditionEditor.Condition.subject",null,null,null,null,null,null,null,null,null,null,null,null));} %></td>
<tr><% _boolean_result=false;try {_boolean_result=((Boolean)(((((Boolean) getObject("NewConditionForm:Invalid")).booleanValue() || ((Boolean) (disableErrorMessages().isDefined(getObject("ErrorCreateCondition")))).booleanValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",31,e);}if (_boolean_result) { %><tr>
<td>
<table border="0" cellspacing="0" cellpadding="4" width="100%" class="error_box ne se">
<tr valign="top">
<td class="error_icon ee"><img src="<%=context.getFormattedValue(context.webRoot(),null)%>/images/error.gif" width="16" height="15" alt="" border="0"/></td>
<td class="error top" width="100%">
<b><% {out.write(localizeISText("NewCondition.ConditionCouldNotBeCreated.error",null,null,null,null,null,null,null,null,null,null,null,null));} %></b><br/><% _boolean_result=false;try {_boolean_result=((Boolean)((((Boolean) (disableErrorMessages().isDefined(getObject("ConditionDescriptor")))).booleanValue() ? Boolean.FALSE : Boolean.TRUE) )).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",40,e);}if (_boolean_result) { %><% {Object temp_obj = (getObject("ConditionDescriptorRegistry:Descriptor(NewConditionForm:ConditionDescriptorID:Value)")); getPipelineDictionary().put("ConditionDescriptor", temp_obj);} %><% } %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("ConditionDescriptor:ConfigErrorTemplate"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",43,e);}if (_boolean_result) { %><% {Object temp_obj = (getObject("NewConditionForm")); getPipelineDictionary().put("ConditionForm", temp_obj);} %><% processOpenTag(response, pageContext, "safetemplateinclude", new TagParameter[] {
new TagParameter("includename",getObject("ConditionDescriptor:ConfigErrorTemplate"))}, 45); %><% } %></td>
</tr>
</table>
</td>
</tr><% } %><% _boolean_result=false;try {_boolean_result=((Boolean)(getObject("NewConditionForm:ConditionType:ValueMissing"))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",54,e);}if (_boolean_result) { %><!-- No condition type selected yet -->
<tr>
<td class="table_detail">
<table cellpadding="0" cellspacing="4" border="0" class="aldi w100">
<tr>
<td class="fielditem2"><% {out.write(localizeISText("sld_enterprise_app.Type.table_header",null,null,null,null,null,null,null,null,null,null,null,null));} %>:</td>
<td><% {out.write("<");out.write("SELECT class=\"inputfield_en\" NAME=\""+context.getFormattedValue(getObject("NewConditionForm:ConditionType:QualifiedName"),null)+"\">");String value, description;while (loop("ConditionTypes",null)){out.write("<");out.write("OPTION ");_boolean_result=false;try {_boolean_result=((Boolean)((((context.getFormattedValue(getObject("NewConditionForm:ConditionType:Value"),null).equals(context.getFormattedValue(getObject("ConditionTypesMap:get(ConditionTypes)"),null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",62,e);}if (_boolean_result) {out.write("SELECTED ");}out.print("VALUE =\"");value = context.getFormattedValue(getObject("ConditionTypes"),null);description = context.getFormattedValue(getObject("ConditionTypesMap:get(ConditionTypes)"),null);value = encodeString(value);description = encodeString(description);out.write(value + "\">");out.write(description + "</OPTION>");}out.write("</SELECT>");} %></td>
<td class="w100"><table cellpadding="0" cellspacing="0" border="0" ><tr>
<td class="button"><input type="submit" class="button" value="<%=context.getFormattedValue(localizeText(context.getFormattedValue("sld_enterprise_app.Apply.button",null)),null)%>" name="newCondition"/></td>
</tr></table></td>
</tr>
</table>
</td>
</tr><% } else {_boolean_result=false;try {_boolean_result=((Boolean)(getObject("NewConditionForm:ConditionDescriptorID:ValueMissing"))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",78,e);}if (_boolean_result) { %><input type="hidden" name="<% {String value = null;try{value=context.getFormattedValue(getObject("NewConditionForm:ConditionType:QualifiedName"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {79}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>" value="<% {String value = null;try{value=context.getFormattedValue(getObject("NewConditionForm:ConditionType:Value"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {79}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>"/>
<!-- No condition selected yet -->
<tr>
<td class="table_detail" >
<table cellpadding="0" cellspacing="4" border="0" class="aldi w100">
<tr>
<td class="label"><label class="label label_light"><% {out.write(localizeISText("ConditionEditor.Condition.subject",null,null,null,null,null,null,null,null,null,null,null,null));} %>:</label></td>
<td><% {out.write("<");out.write("SELECT class=\"inputfield_en\" NAME=\""+context.getFormattedValue(getObject("NewConditionForm:ConditionDescriptorID:QualifiedName"),null)+"\">");String value, description;while (loop("TypeConditionDescriptors",null)){out.write("<");out.write("OPTION ");_boolean_result=false;try {_boolean_result=((Boolean)((( ((Number) getObject("NewConditionForm:ConditionDescriptorID:Value")).doubleValue() ==((Number)(getObject("TypeConditionDescriptors:ID"))).doubleValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",88,e);}if (_boolean_result) {out.write("SELECTED ");}out.print("VALUE =\"");value = context.getFormattedValue(getObject("TypeConditionDescriptors:ID"),null);description = context.getFormattedValue(getObject("TypeConditionDescriptors:Name"),null);value = encodeString(value);description = encodeString(description);out.write(value + "\">");out.write(description + "</OPTION>");}out.write("</SELECT>");} %></td>
<td class="w100"><table cellpadding="0" cellspacing="0" border="0" ><tr>
<td class="button"><input type="submit" class="button" value="<%=context.getFormattedValue(localizeText(context.getFormattedValue("sld_enterprise_app.Apply.button",null)),null)%>" name="newCondition"/></td>
</tr></table></td>
</tr>
</table>
</td>
</tr><% } else { %><input type="hidden" name="<% {String value = null;try{value=context.getFormattedValue(getObject("NewConditionForm:ConditionType:QualifiedName"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {104}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>" value="<% {String value = null;try{value=context.getFormattedValue(getObject("NewConditionForm:ConditionType:Value"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {104}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>"/><% {Object temp_obj = (getObject("ConditionDescriptorRegistry:Descriptor(NewConditionForm:ConditionDescriptorID:Value)")); getPipelineDictionary().put("ConditionDescriptor", temp_obj);} %><!-- now display template configured in ConditionDescriptor --><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("ConditionDescriptor"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",109,e);}if (_boolean_result) { %><tr>
<td><input type="hidden" name="<% {String value = null;try{value=context.getFormattedValue(getObject("NewConditionForm:ConditionDescriptorID:QualifiedName"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {111}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>" value="<% {String value = null;try{value=context.getFormattedValue(getObject("NewConditionForm:ConditionDescriptorID:Value"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {111}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>"/>
<table cellpadding="0" cellspacing="4" border="0" width="100%"><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("ConditionDescriptor:ConfigTemplate"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",113,e);}if (_boolean_result) { %><% {Object temp_obj = (getObject("NewConditionForm")); getPipelineDictionary().put("ConditionForm", temp_obj);} %><tr><td class="aldi"><% processOpenTag(response, pageContext, "safetemplateinclude", new TagParameter[] {
new TagParameter("includename",getObject("ConditionDescriptor:ConfigTemplate"))}, 115); %></td></tr><% } else {_boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("ConditionDescriptor:DisplayTemplate"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",116,e);}if (_boolean_result) { %><tr><td class="aldi"><% processOpenTag(response, pageContext, "safetemplateinclude", new TagParameter[] {
new TagParameter("includename",getObject("ConditionDescriptor:DisplayTemplate"))}, 117); %></td></tr><% }} %></table>
</td>
</tr><% } %><% }} %><tr>
<td width="100%" align="right">
<table cellspacing="4" cellpadding="0" border="0">
<tr><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("ConditionDescriptor"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",130,e);}if (_boolean_result) { %><td class="button"><input type="submit" class="button" value="<%=context.getFormattedValue(localizeText(context.getFormattedValue("sld_enterprise_app.OK.button",null)),null)%>" name="createCondition" /></td><% } %><td class="button"><input type="submit" class="button" value="<%=context.getFormattedValue(localizeText(context.getFormattedValue("sld_enterprise_app.Cancel.button",null)),null)%>" name="cancelCondition" /></td>
</tr>
</table>
</td>
</tr>
</table><% printFooter(out); %>