<%@  page buffer="none" import="java.util.*,java.io.*,com.intershop.beehive.core.internal.template.*,com.intershop.beehive.core.internal.template.isml.*,com.intershop.beehive.core.capi.log.*,com.intershop.beehive.core.capi.resource.*,com.intershop.beehive.core.capi.util.UUIDMgr,com.intershop.beehive.core.capi.util.XMLHelper,com.intershop.beehive.foundation.util.*,com.intershop.beehive.core.internal.url.*,com.intershop.beehive.core.internal.resource.*,com.intershop.beehive.core.internal.wsrp.*,com.intershop.beehive.core.capi.pipeline.PipelineDictionary,com.intershop.beehive.core.capi.naming.NamingMgr,com.intershop.beehive.core.capi.pagecache.PageCacheMgr,com.intershop.beehive.core.capi.request.SessionMgr,com.intershop.beehive.core.internal.request.SessionMgrImpl,com.intershop.beehive.core.pipelet.PipelineConstants" extends="com.intershop.beehive.core.internal.template.AbstractTemplate" %><% 
boolean _boolean_result=false;
TemplateExecutionConfig context = getTemplateExecutionConfig();
createTemplatePageConfig(context.getServletRequest());
printHeader(out);
 %><% %><%@ page contentType="text/html;charset=utf-8" %><%setEncodingType("text/html"); %><tr><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("CurrentChannelPermissionMap:SLD_SYNDICATE_CATALOGS"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",4,e);}if (_boolean_result) { %> 
<td class="w s center">
<input type="hidden" name="RepositoryUUID" value="<%=context.getFormattedValue(getObject("Repository:UUID"),null)%>"/>
<input type="checkbox" name="SelectedRepositoryUUID" value="<%=context.getFormattedValue(getObject("Repository:UUID"),null)%>" <% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("Checked"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",7,e);}if (_boolean_result) { %>checked="checked"<% } %>/>
</td><% } %><td class="table_detail w s"><% _boolean_result=false;try {_boolean_result=((Boolean)((( ((Number) getObject("Repository:TypeCode")).doubleValue() ==((Number)(new Double(21))).doubleValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",11,e);}if (_boolean_result) { %><b><% {out.write(localizeISText("IncParentRepository_32.MasterRepository.table_detail",null,null,null,null,null,null,null,null,null,null,null,null));} %></b><% } else { %><b><% {out.write(localizeISText("IncParentRepository_32.ChannelRepository.table_detail",null,null,null,null,null,null,null,null,null,null,null,null));} %></b><% } %>&nbsp;
</td>
<td class="table_detail w s"><% _boolean_result=false;try {_boolean_result=((Boolean)((( ((Number) getObject("CurrentChannel:SyncRecord(Repository):StopTime:Time")).doubleValue() !=((Number)(new Double(0))).doubleValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",18,e);}if (_boolean_result) { %><% {String value = null;try{value=context.getFormattedValue(context.getFormattedValue(getObject("CurrentChannel:SyncRecord(Repository):StopTime"),new Integer(DATE_SHORT)),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {19}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>&nbsp;
<% {String value = null;try{value=context.getFormattedValue(context.getFormattedValue(getObject("CurrentChannel:SyncRecord(Repository):StopTime"),new Integer(DATE_TIME)),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {20}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %><% } else { %><% {out.write(localizeISText("IncParentRepository_32.None.table_detail",null,null,null,null,null,null,null,null,null,null,null,null));} %><% } %></td>
<td class="table_detail w s"><% {String value = null;try{value=context.getFormattedValue(getObject("Products:ElementCount"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {25}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %><% _boolean_result=false;try {_boolean_result=((Boolean)(((((Boolean) (disableErrorMessages().isDefined(getObject("Clipboard")))).booleanValue() && ((Boolean) ((( ((Number) getObject("Clipboard:ObjectUUIDsCount")).doubleValue() >((Number)(new Double(0))).doubleValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",26,e);}if (_boolean_result) { %>(<% {out.write(localizeISText("IncParentRepository_32.0SelectedForSynchronization.table_detail",null,null,context.getFormattedValue(getObject("Clipboard:ObjectUUIDsCount"),null),null,null,null,null,null,null,null,null,null));} %>)
<% } %></td>
<td class="table_detail w s">
<select name="<%=context.getFormattedValue(getObject("Repository:UUID"),null)%>_Interval" class="inputfield_en"
<% _boolean_result=false;try {_boolean_result=((Boolean)((((Boolean) (disableErrorMessages().isDefined(getObject("CurrentChannelPermissionMap:SLD_SYNDICATE_CATALOGS")))).booleanValue() ? Boolean.FALSE : Boolean.TRUE) )).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",32,e);}if (_boolean_result) { %>
disabled="disabled"
<% } %>
/> 
<option value="0" <% _boolean_result=false;try {_boolean_result=((Boolean)((( ((Number) new Double(0)).doubleValue() ==((Number)(getObject("CurrentChannel:SyncRecord(Repository):Interval"))).doubleValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",36,e);}if (_boolean_result) { %>selected="selected"<% } %>><% {out.write(localizeISText("IncParentRepository_32.ManualSyncOnly.option",null,null,null,null,null,null,null,null,null,null,null,null));} %></option>
<option value="3600000" <% _boolean_result=false;try {_boolean_result=((Boolean)((( ((Number) new Double(3600000)).doubleValue() ==((Number)(getObject("CurrentChannel:SyncRecord(Repository):Interval"))).doubleValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",37,e);}if (_boolean_result) { %>selected="selected"<% } %>><% {out.write(localizeISText("IncParentRepository_32.EveryHour.option",null,null,null,null,null,null,null,null,null,null,null,null));} %></option>
<option value="21600000" <% _boolean_result=false;try {_boolean_result=((Boolean)((( ((Number) new Double(21600000)).doubleValue() ==((Number)(getObject("CurrentChannel:SyncRecord(Repository):Interval"))).doubleValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",38,e);}if (_boolean_result) { %>selected="selected"<% } %>><% {out.write(localizeISText("IncParentRepository_32.Every6Hours.option",null,null,null,null,null,null,null,null,null,null,null,null));} %></option>
<option value="43200000" <% _boolean_result=false;try {_boolean_result=((Boolean)((( ((Number) new Double(43200000)).doubleValue() ==((Number)(getObject("CurrentChannel:SyncRecord(Repository):Interval"))).doubleValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",39,e);}if (_boolean_result) { %>selected="selected"<% } %>><% {out.write(localizeISText("IncParentRepository_32.Every12Hours.option",null,null,null,null,null,null,null,null,null,null,null,null));} %></option>
<option value="86400000" <% _boolean_result=false;try {_boolean_result=((Boolean)((( ((Number) new Double(86400000)).doubleValue() ==((Number)(getObject("CurrentChannel:SyncRecord(Repository):Interval"))).doubleValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",40,e);}if (_boolean_result) { %>selected="selected"<% } %>><% {out.write(localizeISText("IncParentRepository_32.EveryDay.option",null,null,null,null,null,null,null,null,null,null,null,null));} %></option>
<option value="604800000" <% _boolean_result=false;try {_boolean_result=((Boolean)((( ((Number) new Double(604800000)).doubleValue() ==((Number)(getObject("CurrentChannel:SyncRecord(Repository):Interval"))).doubleValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",41,e);}if (_boolean_result) { %>selected="selected"<% } %>><% {out.write(localizeISText("IncParentRepository_32.EveryWeek.option",null,null,null,null,null,null,null,null,null,null,null,null));} %></option>
</select>&nbsp;
</td> 
<td class="table_detail w e s">
<a href="<%=context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewChangedProducts_32-ListAll",null))),(new URLParameterSet().addURLParameter(context.getFormattedValue("RepositoryUUID",null),context.getFormattedValue(getObject("Repository:UUID"),null)))),null)%>" class="table_detail_link"><% {out.write(localizeISText("IncParentRepository_32.Details.link",null,null,null,null,null,null,null,null,null,null,null,null));} %></a>
</td> 
</tr><% printFooter(out); %>