<%@  page buffer="none" import="java.util.*,java.io.*,com.intershop.beehive.core.internal.template.*,com.intershop.beehive.core.internal.template.isml.*,com.intershop.beehive.core.capi.log.*,com.intershop.beehive.core.capi.resource.*,com.intershop.beehive.core.capi.util.UUIDMgr,com.intershop.beehive.core.capi.util.XMLHelper,com.intershop.beehive.foundation.util.*,com.intershop.beehive.core.internal.url.*,com.intershop.beehive.core.internal.resource.*,com.intershop.beehive.core.internal.wsrp.*,com.intershop.beehive.core.capi.pipeline.PipelineDictionary,com.intershop.beehive.core.capi.naming.NamingMgr,com.intershop.beehive.core.capi.pagecache.PageCacheMgr,com.intershop.beehive.core.capi.request.SessionMgr,com.intershop.beehive.core.internal.request.SessionMgrImpl,com.intershop.beehive.core.pipelet.PipelineConstants" extends="com.intershop.beehive.core.internal.template.AbstractTemplate" %><% 
boolean _boolean_result=false;
TemplateExecutionConfig context = getTemplateExecutionConfig();
createTemplatePageConfig(context.getServletRequest());
printHeader(out);
 %><% %><%@ page contentType="text/html;charset=utf-8" %><%setEncodingType("text/html"); %><%@page import="com.intershop.sellside.storefront.base.internal.paging.PagingGroupedByInterval"%><%@page import="com.intershop.sellside.storefront.base.capi.paging.AbstractPagingCalculator"%><%
	Object cp =  getObject("currentpage");
	Object pc =  getObject("pagecount");
	
	AbstractPagingCalculator paging = new PagingGroupedByInterval(cp, pc, 14,10);
	getPipelineDictionary().put("barEntries", paging.createCalculatedPagingIterator());

%><div class="col-md-3 col-sm-3 col-xs-4"><% {out.flush();processLocalIncludeByServer((com.intershop.beehive.core.capi.request.ServletResponse)response,"modules/paging/elements/TotalItems.isml", null, "13");} %></div><% _boolean_result=false;try {_boolean_result=((Boolean)((((Boolean) ((disableErrorMessages().isDefined(getObject("sortvalue"))))).booleanValue() ? Boolean.FALSE : Boolean.TRUE) )).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",16,e);}if (_boolean_result) { %><% {Object temp_obj = (getObject("ListNavigationVO:SortingAttribute")); getPipelineDictionary().put("sortvalue", temp_obj);} %><% } %><% _boolean_result=false;try {_boolean_result=((Boolean)((((Boolean) ((disableErrorMessages().isDefined(getObject("pagesize"))))).booleanValue() ? Boolean.FALSE : Boolean.TRUE) )).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",17,e);}if (_boolean_result) { %><% {Object temp_obj = (getObject("ListNavigationVO:PageSize")); getPipelineDictionary().put("pagesize", temp_obj);} %><% } %><div class="pagination-sites col-md-9 col-sm-9 col-xs-8">
<ul class="pagination-site-list"><% _boolean_result=false;try {_boolean_result=((Boolean)((( ((Number) getObject("currentpage")).doubleValue() >((Number)(new Double(0))).doubleValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",23,e);}if (_boolean_result) { %> 
<li class="pagination-site-list-previous"><% processOpenTag(response, pageContext, "createpaginglink", new TagParameter[] {
new TagParameter("result","paginglink"),
new TagParameter("pipelinename",getObject("pipeline")),
new TagParameter("sortvalue",getObject("sortvalue")),
new TagParameter("pagesize",getObject("pagesize")),
new TagParameter("params",getObject("params")),
new TagParameter("pagenumber",context.getFormattedValue((new Double( ((Number) getObject("currentpage")).doubleValue() -((Number) new Double(1)).doubleValue())),"0"))}, 25); %><a href="<% {String value = null;try{value=context.getFormattedValue(getObject("paginglink"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {32}",e);}if (value==null) value="";out.write(value);} %>"
<% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("hijax"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",33,e);}if (_boolean_result) { %>data-hijax="<% {String value = null;try{value=context.getFormattedValue(getObject("hijax"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {33}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %><% } %> 
title="<% {out.write(localizeISText("common.module.pagination.previous.title.link","",null,null,null,null,null,null,null,null,null,null,null));} %>">&<%=context.getFormattedValue("#",null)%>171;</a>
</li><% out.print(context.prepareWAPlacement("CANONICAL")); %><link rel="prev" href="<% {String value = null;try{value=context.getFormattedValue(getObject("paginglink"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {36}",e);}if (value==null) value="";out.write(value);} %>" /><% out.print("</waplacement>"); %><% } else { %><li class="pagination-site-list-previous">&<%=context.getFormattedValue("#",null)%>171;</li><% } %><% while (loop("barEntries","e",null)) { %><li class="<% _boolean_result=false;try {_boolean_result=((Boolean)((((context.getFormattedValue(getObject("e:Value"),null).equals(context.getFormattedValue(context.getFormattedValue(getObject("currentpage"),"0"),null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",45,e);}if (_boolean_result) { %> pagination-site-active<% } %>"><% _boolean_result=false;try {_boolean_result=((Boolean)((((context.getFormattedValue(getObject("e:Value"),null).equals(context.getFormattedValue(context.getFormattedValue(getObject("currentpage"),"0"),null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",46,e);}if (_boolean_result) { %><% {String value = null;try{value=context.getFormattedValue(getObject("e:Key"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {47}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %><% } else { %><a href="<% processOpenTag(response, pageContext, "paginglink", new TagParameter[] {
new TagParameter("pipelinename",getObject("pipeline")),
new TagParameter("sortvalue",getObject("sortvalue")),
new TagParameter("pagesize",getObject("pagesize")),
new TagParameter("params",getObject("params")),
new TagParameter("pagenumber",getObject("e:Value"))}, 49); %>"
<% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("hijax"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",55,e);}if (_boolean_result) { %>data-hijax="<% {String value = null;try{value=context.getFormattedValue(getObject("hijax"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {55}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %><% } %> 
title="to page <% {String value = null;try{value=context.getFormattedValue(getObject("e:Key"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {56}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>">
<span class="pagination-hide"><% {out.write(localizeISText("common.module.pagination.topage.text","",null,null,null,null,null,null,null,null,null,null,null));} %></span><% {String value = null;try{value=context.getFormattedValue(getObject("e:Key"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {58}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %><span class="pagination-hide"><% {out.write(localizeISText("common.module.pagination.of.text","",null,null,null,null,null,null,null,null,null,null,null));} %><% {String value = null;try{value=context.getFormattedValue(getObject("pagecount"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {60}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %></span>
</a><% } %></li><% } %><% _boolean_result=false;try {_boolean_result=((Boolean)((( ((Number) getObject("currentpage")).doubleValue() <((Number)(((new Double( ((Number) getObject("pagecount")).doubleValue() -((Number) new Double(1)).doubleValue()))))).doubleValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",70,e);}if (_boolean_result) { %><li class="pagination-list-next"><% processOpenTag(response, pageContext, "createpaginglink", new TagParameter[] {
new TagParameter("result","paginglink"),
new TagParameter("pipelinename",getObject("pipeline")),
new TagParameter("sortvalue",getObject("sortvalue")),
new TagParameter("pagesize",getObject("pagesize")),
new TagParameter("params",getObject("params")),
new TagParameter("pagenumber",context.getFormattedValue((new Double( ((Number) getObject("currentpage")).doubleValue() +((Number) new Double(1)).doubleValue())),"0"))}, 72); %><a href="<% {String value = null;try{value=context.getFormattedValue(getObject("paginglink"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {80}",e);}if (value==null) value="";out.write(value);} %>"
<% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("hijax"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",81,e);}if (_boolean_result) { %>data-hijax="<% {String value = null;try{value=context.getFormattedValue(getObject("hijax"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {81}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %><% } %> 
title="<% {out.write(localizeISText("common.module.pagination.next.title.link","",null,null,null,null,null,null,null,null,null,null,null));} %>">&<%=context.getFormattedValue("#",null)%>187;</a>
</li><% out.print(context.prepareWAPlacement("CANONICAL")); %><link rel="next" href="<% {String value = null;try{value=context.getFormattedValue(getObject("paginglink"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {84}",e);}if (value==null) value="";out.write(value);} %>" /><% out.print("</waplacement>"); %><% } else { %><li class="pagination-list-next">&<%=context.getFormattedValue("#",null)%>187;</li><% } %></ul>
</div><% printFooter(out); %>