<%@  page buffer="none" import="java.util.*,java.io.*,com.intershop.beehive.core.internal.template.*,com.intershop.beehive.core.internal.template.isml.*,com.intershop.beehive.core.capi.log.*,com.intershop.beehive.core.capi.resource.*,com.intershop.beehive.core.capi.util.UUIDMgr,com.intershop.beehive.core.capi.util.XMLHelper,com.intershop.beehive.foundation.util.*,com.intershop.beehive.core.internal.url.*,com.intershop.beehive.core.internal.resource.*,com.intershop.beehive.core.internal.wsrp.*,com.intershop.beehive.core.capi.pipeline.PipelineDictionary,com.intershop.beehive.core.capi.naming.NamingMgr,com.intershop.beehive.core.capi.pagecache.PageCacheMgr,com.intershop.beehive.core.capi.request.SessionMgr,com.intershop.beehive.core.internal.request.SessionMgrImpl,com.intershop.beehive.core.pipelet.PipelineConstants" extends="com.intershop.beehive.core.internal.template.AbstractTemplate" %><% 
boolean _boolean_result=false;
TemplateExecutionConfig context = getTemplateExecutionConfig();
createTemplatePageConfig(context.getServletRequest());
printHeader(out);
 %><% %><%@ page contentType="text/html;charset=utf-8" %><%setEncodingType("text/html"); %><% processOpenTag(response, pageContext, "createmap", new TagParameter[] {
new TagParameter("key1","ContentRepositoryUUID"),
new TagParameter("key0","PageletEntryPointUUID"),
new TagParameter("value1",getObject("ContentRepository:UUID")),
new TagParameter("value0",getObject("PageletEntryPoint:UUID")),
new TagParameter("mapname","Params")}, 2); %><% {try{executePipeline("ViewPageletEntryPointProperties-IsCopyPossible",((java.util.Map)(getObject("Params"))),"IsCopyPossible");}catch(Exception e){Logger.error(this,"ISPIPELINE failed. Line: 3.",e);}} %><% _boolean_result=false;try {_boolean_result=((Boolean)(getObject("IsCopyPossible:Result"))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",3,e);}if (_boolean_result) { %><a href="<%=context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewPageletEntryPointProperties-Copy",null))),(new URLParameterSet().addURLParameter(context.getFormattedValue("ContentRepositoryUUID",null),context.getFormattedValue(getObject("ContentRepository:UUID"),null))).addURLParameter(context.getFormattedValue("PageletEntryPointUUID",null),context.getFormattedValue(getObject("PageletEntryPoint:UUID"),null)).addURLParameter(context.getFormattedValue("CopyOfPrefix",null),context.getFormattedValue(getObject("CopyOfPrefix"),null))),null)%>" class="copy_pagelet"><img src="<%=context.getFormattedValue(context.webRoot(),null)%>/images/copy_pagelet.gif" alt="<%=context.getFormattedValue(localizeText(context.getFormattedValue("CopyPageletEntryPoint.CopyPage.alt",null)),null)%>" title="<%=context.getFormattedValue(localizeText(context.getFormattedValue("CopyPageletEntryPoint.CopyPage.title",null)),null)%>" border="0" /></a>&nbsp;<% } %><% printFooter(out); %>