<%@  page buffer="none" import="java.util.*,java.io.*,com.intershop.beehive.core.internal.template.*,com.intershop.beehive.core.internal.template.isml.*,com.intershop.beehive.core.capi.log.*,com.intershop.beehive.core.capi.resource.*,com.intershop.beehive.core.capi.util.UUIDMgr,com.intershop.beehive.core.capi.util.XMLHelper,com.intershop.beehive.foundation.util.*,com.intershop.beehive.core.internal.url.*,com.intershop.beehive.core.internal.resource.*,com.intershop.beehive.core.internal.wsrp.*,com.intershop.beehive.core.capi.pipeline.PipelineDictionary,com.intershop.beehive.core.capi.naming.NamingMgr,com.intershop.beehive.core.capi.pagecache.PageCacheMgr,com.intershop.beehive.core.capi.request.SessionMgr,com.intershop.beehive.core.internal.request.SessionMgrImpl,com.intershop.beehive.core.pipelet.PipelineConstants" extends="com.intershop.beehive.core.internal.template.AbstractTemplate" %><% 
boolean _boolean_result=false;
TemplateExecutionConfig context = getTemplateExecutionConfig();
createTemplatePageConfig(context.getServletRequest());
printHeader(out);
 %><% %><%@ page contentType="text/html;charset=utf-8" %><%setEncodingType("text/html"); %><% {out.flush();processLocalIncludeByServer((com.intershop.beehive.core.capi.request.ServletResponse)response,"modules/Modules", null, "2");} %><% _boolean_result=false;try {_boolean_result=((Boolean)((hasLoopElements("PageletConfigurationParameters:Products") ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",4,e);}if (_boolean_result) { %><% {out.flush();processLocalIncludeByServer((com.intershop.beehive.core.capi.request.ServletResponse)response,"component/common/inc/CollectionItemPrefix.isml", null, "5");} %><% {Object temp_obj = (getObject("PageletConfigurationParameters:Products:Iterator")); getPipelineDictionary().put("ProductBOs", temp_obj);} %><% {try{executePipeline("FireTrackingEvents-ViewProductList",((java.util.Map)(((new ParameterMap().addParameter(new ParameterEntry("CurrentSession",getObject("CurrentSession")))).addParameter(new ParameterEntry("CurrentRequest",getObject("CurrentRequest"))).addParameter(new ParameterEntry("ProductList",getObject("ProductBOs"))).addParameter(new ParameterEntry("PageName",getObject("PageletConfigurationParameters:Title"))).addParameter(new ParameterEntry("PageType",""))))),"dict");}catch(Exception e){Logger.error(this,"ISPIPELINE failed. Line: 9.",e);}} %><div
class="product-list-container <% {String value = null;try{value=context.getFormattedValue(getObject("PageletConfigurationParameters:CSSClass"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {19}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>"><% _boolean_result=false;try {_boolean_result=((Boolean)(((!((Boolean) ((((context.getFormattedValue(getObject("RenderedInCollection"),null).equals(context.getFormattedValue("true",null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue() && ((Boolean) (disableErrorMessages().isDefined(getObject("PageletConfigurationParameters:Title")))).booleanValue() && ((Boolean) (((!(context.getFormattedValue(getObject("PageletConfigurationParameters:Title"),null).equals(context.getFormattedValue("",null)))) ? Boolean.TRUE : Boolean.FALSE))).booleanValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",20,e);}if (_boolean_result) { %><h2><% {String value = null;try{value=context.getFormattedValue(getObject("PageletConfigurationParameters:Title"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {23}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %></h2><% } %><% processOpenTag(response, pageContext, "productlist", new TagParameter[] {
new TagParameter("numberOfProductsPerSlide",getObject("PageletConfigurationParameters:SlideItems")),
new TagParameter("listBehavior",getObject("PageletConfigurationParameters:ListStyle")),
new TagParameter("ProductBOs",getObject("ProductBOs")),
new TagParameter("listItemCssClass",getObject("PageletConfigurationParameters:ListItemCSSClass")),
new TagParameter("viewContext",getObject("PageletConfigurationParameters:ProductView"))}, 26); %></div><% {out.flush();processLocalIncludeByServer((com.intershop.beehive.core.capi.request.ServletResponse)response,"component/common/inc/CollectionItemSuffix.isml", null, "35");} %><% } %><% printFooter(out); %>