<%@  page buffer="none" import="java.util.*,java.io.*,com.intershop.beehive.core.internal.template.*,com.intershop.beehive.core.internal.template.isml.*,com.intershop.beehive.core.capi.log.*,com.intershop.beehive.core.capi.resource.*,com.intershop.beehive.core.capi.util.UUIDMgr,com.intershop.beehive.core.capi.util.XMLHelper,com.intershop.beehive.foundation.util.*,com.intershop.beehive.core.internal.url.*,com.intershop.beehive.core.internal.resource.*,com.intershop.beehive.core.internal.wsrp.*,com.intershop.beehive.core.capi.pipeline.PipelineDictionary,com.intershop.beehive.core.capi.naming.NamingMgr,com.intershop.beehive.core.capi.pagecache.PageCacheMgr,com.intershop.beehive.core.capi.request.SessionMgr,com.intershop.beehive.core.internal.request.SessionMgrImpl,com.intershop.beehive.core.pipelet.PipelineConstants" extends="com.intershop.beehive.core.internal.template.AbstractTemplate" %><% 
boolean _boolean_result=false;
TemplateExecutionConfig context = getTemplateExecutionConfig();
createTemplatePageConfig(context.getServletRequest());
printHeader(out);
 %><% %><%@ page contentType="text/html;charset=utf-8" %><%setEncodingType("text/html"); %><!-- Main Content -->
<table cellpadding="0" cellspacing="0" border="0" class="w100">
<!-- Navigation and Content Area -->
<tr>
<td class="breadcrumb"><a href="<%=context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("Monitor-Start",null),context.getFormattedValue("",null),context.getFormattedValue("SMC",null)))),null)%>" class="breadcrumb"><% {out.write(localizeISText("monitor.Monitoring.link","",null,null,null,null,null,null,null,null,null,null,null));} %></a>&nbsp;&gt;&nbsp;<a href="<%=context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("Monitor-BackgroundMonitoring",null),context.getFormattedValue("",null),context.getFormattedValue("SMC",null)))),null)%>" class="breadcrumb"><% {out.write(localizeISText("monitor.Background.link","",null,null,null,null,null,null,null,null,null,null,null));} %></a>&nbsp;&gt;&nbsp; <% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("MemoryChart"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",7,e);}if (_boolean_result) { %><% {out.write(localizeISText("monitor.MemoryCharts.link","",null,null,null,null,null,null,null,null,null,null,null));} %><% } %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("SessionChart"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",7,e);}if (_boolean_result) { %><% {out.write(localizeISText("monitor.SessionCharts.link","",null,null,null,null,null,null,null,null,null,null,null));} %><% } %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("PerformanceChart"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",7,e);}if (_boolean_result) { %><% {out.write(localizeISText("monitor.PerformanceCharts.link","",null,null,null,null,null,null,null,null,null,null,null));} %><% } %></td>
</tr>
<tr><td><img src="<%=context.getFormattedValue(context.webRoot(),null)%>/images/space.gif" width="1" height="6" alt="" border="0"/></td></tr>
<tr>
<td><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("MemoryChart"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",12,e);}if (_boolean_result) { %><% {Object temp_obj = ("Memory"); getPipelineDictionary().put("ChartTarget", temp_obj);} %> 
<% } %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("SessionChart"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",15,e);}if (_boolean_result) { %><% {Object temp_obj = ("Session"); getPipelineDictionary().put("ChartTarget", temp_obj);} %> 
<% } %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("PerformanceChart"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",18,e);}if (_boolean_result) { %><% {Object temp_obj = ("Performance"); getPipelineDictionary().put("ChartTarget", temp_obj);} %><% } %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("Start_Day"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",22,e);}if (_boolean_result) { %><% {out.flush();%><%@page import="com.intershop.beehive.core.capi.url.*"%><%URLRewriteHandler handler = getTemplateExecutionConfig().getURLRewriteHandler();
try
{
getTemplateExecutionConfig().setURLRewriteHandler(NullURLRewriteHandler.getInstance());
processRemoteIncludeAutomatic((com.intershop.beehive.core.capi.request.ServletResponse)response,context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewServerSelection-Start",null))),(new URLParameterSet().addURLParameter(context.getFormattedValue("TargetPipeline",null),context.getFormattedValue(context.getFormattedValue("ViewChart-",null) + context.getFormattedValue(getObject("ChartTarget"),null),null))).addURLParameter(context.getFormattedValue("TargetServerID",null),context.getFormattedValue(getObject("TargetServerID"),null)).addURLParameter(context.getFormattedValue("SelectDateRange",null),context.getFormattedValue(getObject("TRUE"),null)).addURLParameter(context.getFormattedValue("Start_Day",null),context.getFormattedValue(getObject("Start_Day"),null)).addURLParameter(context.getFormattedValue("Start_Time",null),context.getFormattedValue(getObject("Start_Time"),null)).addURLParameter(context.getFormattedValue("End_Day",null),context.getFormattedValue(getObject("End_Day"),null)).addURLParameter(context.getFormattedValue("End_Time",null),context.getFormattedValue(getObject("End_Time"),null))),null), null, null, "23");}
finally
{
    getTemplateExecutionConfig().setURLRewriteHandler(handler);
}} %><% } else { %><% {out.flush();%><%@page import="com.intershop.beehive.core.capi.url.*"%><%URLRewriteHandler handler = getTemplateExecutionConfig().getURLRewriteHandler();
try
{
getTemplateExecutionConfig().setURLRewriteHandler(NullURLRewriteHandler.getInstance());
processRemoteIncludeAutomatic((com.intershop.beehive.core.capi.request.ServletResponse)response,context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewServerSelection-Start",null))),(new URLParameterSet().addURLParameter(context.getFormattedValue("TargetPipeline",null),context.getFormattedValue(context.getFormattedValue("ViewChart-",null) + context.getFormattedValue(getObject("ChartTarget"),null),null))).addURLParameter(context.getFormattedValue("TargetServerID",null),context.getFormattedValue(getObject("TargetServerID"),null)).addURLParameter(context.getFormattedValue("SelectDateRange",null),context.getFormattedValue(getObject("TRUE"),null))),null), null, null, "25");}
finally
{
    getTemplateExecutionConfig().setURLRewriteHandler(handler);
}} %> 
<% } %></td>
</tr>
<tr>
<td><img src="<%=context.getFormattedValue(context.webRoot(),null)%>/images/spacer.gif" width="1" height="5" border="0" alt=""/></td> <!-- blank line, separates server select from content -->
</tr><% _boolean_result=false;try {_boolean_result=((Boolean)((((Boolean) (disableErrorMessages().isDefined(getObject("ErrorCode")))).booleanValue() ? Boolean.FALSE : Boolean.TRUE) )).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",35,e);}if (_boolean_result) { %><!-- Content Area -->
<tr>
<td>
<table cellpadding="0" cellspacing="0" border="0" class="aldi w100">
<tr>
<td class="table_title s"><% {out.write(localizeISText("monitor_chart.BackgroundMonitoring.table_title","",null,null,null,null,null,null,null,null,null,null,null));} %> - <% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("MemoryChart"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",41,e);}if (_boolean_result) { %><% {out.write(localizeISText("monitor.MemoryCharts.table_title","",null,null,null,null,null,null,null,null,null,null,null));} %><% } %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("SessionChart"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",41,e);}if (_boolean_result) { %><% {out.write(localizeISText("monitor.SessionCharts.table_title","",null,null,null,null,null,null,null,null,null,null,null));} %><% } %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("PerformanceChart"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",41,e);}if (_boolean_result) { %><% {out.write(localizeISText("monitor.PerformanceCharts.table_title","",null,null,null,null,null,null,null,null,null,null,null));} %><% } %></td>
</tr>
<tr>
<td class="table_title_description"><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("MemoryChart"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",45,e);}if (_boolean_result) { %><% {out.write(localizeISText("monitor.PageDisplaysMemoryUsageInformation.table_title_description","",null,null,null,null,null,null,null,null,null,null,null));} %><% } %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("SessionChart"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",46,e);}if (_boolean_result) { %><% {out.write(localizeISText("monitor.PageDisplaysSessionInformation.table_title_description","",null,null,null,null,null,null,null,null,null,null,null));} %><% } %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("PerformanceChart"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",47,e);}if (_boolean_result) { %><% {out.write(localizeISText("monitor.PageDisplaysDetailedPerformanceInformation.table_title_description","",null,null,null,null,null,null,null,null,null,null,null));} %><% } %></td>
</tr>
</table>
</td>
</tr>
<tr><td><img src="<%=context.getFormattedValue(context.webRoot(),null)%>/images/space.gif" width="1" height="6" alt="" border="0"/></td></tr>
<tr>
<td>
<table cellpadding="0" cellspacing="0" border="0" class="w100">
<tr>
<td colspan="2">
<table width="100%" cellpadding="0" cellspacing="0" border="0"><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("MemoryChart"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",60,e);}if (_boolean_result) { %><tr><td colspan="2"><img src="<%=context.getFormattedValue(context.webRoot(),null)%>/images/spacer.gif" width="1" height="20" border="0" alt=""/></td></tr>
<tr>
<td colspan="2">
<img src="<%=context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("Monitor-DisplayLineChart",null))),(new URLParameterSet().addURLParameter(context.getFormattedValue("title",null),context.getFormattedValue("Process Memory",null))).addURLParameter(context.getFormattedValue("ytitle",null),context.getFormattedValue("(Bytes)",null)).addURLParameter(context.getFormattedValue("height",null),context.getFormattedValue("400",null)).addURLParameter(context.getFormattedValue("width",null),context.getFormattedValue("750",null)).addURLParameter(context.getFormattedValue("series0",null),context.getFormattedValue("Total Size",null)).addURLParameter(context.getFormattedValue("series1",null),context.getFormattedValue("In-Memory Size",null)).addURLParameter(context.getFormattedValue("startDate",null),context.getFormattedValue(getObject("StartDateTimeStamp"),null)).addURLParameter(context.getFormattedValue("endDate",null),context.getFormattedValue(getObject("EndDateTimeStamp"),null)).addURLParameter(context.getFormattedValue("minimumGapSize",null),context.getFormattedValue(getObject("MinimumGapSize"),null))),null)%>" alt=""/>
</td>
</tr>
<tr><td colspan="2"><img src="<%=context.getFormattedValue(context.webRoot(),null)%>/images/spacer.gif" width="1" height="20" border="0" alt=""/></td></tr><% } %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("MemoryChart"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",80,e);}if (_boolean_result) { %><tr><td colspan="2"><img src="<%=context.getFormattedValue(context.webRoot(),null)%>/images/spacer.gif" width="1" height="20" border="0" alt=""/></td></tr>
<tr>
<td colspan="2">
<img src="<%=context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("Monitor-DisplayLineChart",null))),(new URLParameterSet().addURLParameter(context.getFormattedValue("title",null),context.getFormattedValue("Java VM Memory",null))).addURLParameter(context.getFormattedValue("ytitle",null),context.getFormattedValue("(Bytes)",null)).addURLParameter(context.getFormattedValue("height",null),context.getFormattedValue("400",null)).addURLParameter(context.getFormattedValue("width",null),context.getFormattedValue("750",null)).addURLParameter(context.getFormattedValue("series0",null),context.getFormattedValue("Total Heap",null)).addURLParameter(context.getFormattedValue("series1",null),context.getFormattedValue("Used Heap",null)).addURLParameter(context.getFormattedValue("startDate",null),context.getFormattedValue(getObject("StartDateTimeStamp"),null)).addURLParameter(context.getFormattedValue("endDate",null),context.getFormattedValue(getObject("EndDateTimeStamp"),null)).addURLParameter(context.getFormattedValue("minimumGapSize",null),context.getFormattedValue(getObject("MinimumGapSize"),null))),null)%>" alt=""/>
</td>
</tr>
<tr><td colspan="2"><img src="<%=context.getFormattedValue(context.webRoot(),null)%>/images/spacer.gif" width="1" height="20" border="0" alt=""/></td></tr><% } %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("MemoryChart"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",100,e);}if (_boolean_result) { %><tr><td colspan="2"><img src="<%=context.getFormattedValue(context.webRoot(),null)%>/images/spacer.gif" width="1" height="20" border="0" alt=""/></td></tr>
<tr>
<td colspan="2">
<img src="<%=context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("Monitor-DisplayLineChart",null))),(new URLParameterSet().addURLParameter(context.getFormattedValue("title",null),context.getFormattedValue("ORM Cache",null))).addURLParameter(context.getFormattedValue("ytitle",null),context.getFormattedValue("(Count)",null)).addURLParameter(context.getFormattedValue("height",null),context.getFormattedValue("400",null)).addURLParameter(context.getFormattedValue("width",null),context.getFormattedValue("750",null)).addURLParameter(context.getFormattedValue("series0",null),context.getFormattedValue("Cache Size",null)).addURLParameter(context.getFormattedValue("startDate",null),context.getFormattedValue(getObject("StartDateTimeStamp"),null)).addURLParameter(context.getFormattedValue("endDate",null),context.getFormattedValue(getObject("EndDateTimeStamp"),null)).addURLParameter(context.getFormattedValue("minimumGapSize",null),context.getFormattedValue(getObject("MinimumGapSize"),null))),null)%>" alt=""/>
</td>
</tr>
<tr><td colspan="2"><img src="<%=context.getFormattedValue(context.webRoot(),null)%>/images/spacer.gif" width="1" height="20" border="0" alt=""/></td></tr><% } %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("SessionChart"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",119,e);}if (_boolean_result) { %><tr><td colspan="2"><img src="<%=context.getFormattedValue(context.webRoot(),null)%>/images/spacer.gif" width="1" height="20" border="0" alt=""/></td></tr>
<tr>
<td colspan="2">
<img src="<%=context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("Monitor-DisplayLineChart",null))),(new URLParameterSet().addURLParameter(context.getFormattedValue("title",null),context.getFormattedValue("Total Sessions",null))).addURLParameter(context.getFormattedValue("ytitle",null),context.getFormattedValue("(count)",null)).addURLParameter(context.getFormattedValue("height",null),context.getFormattedValue("400",null)).addURLParameter(context.getFormattedValue("width",null),context.getFormattedValue("750",null)).addURLParameter(context.getFormattedValue("series0",null),context.getFormattedValue("Total Sessions",null)).addURLParameter(context.getFormattedValue("startDate",null),context.getFormattedValue(getObject("StartDateTimeStamp"),null)).addURLParameter(context.getFormattedValue("endDate",null),context.getFormattedValue(getObject("EndDateTimeStamp"),null)).addURLParameter(context.getFormattedValue("minimumGapSize",null),context.getFormattedValue(getObject("MinimumGapSize"),null))),null)%>" alt=""/>
</td>
</tr>
<tr><td colspan="2"><img src="<%=context.getFormattedValue(context.webRoot(),null)%>/images/spacer.gif" width="1" height="20" border="0" alt=""/></td></tr><% } %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("SessionChart"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",138,e);}if (_boolean_result) { %><tr><td colspan="2"><img src="<%=context.getFormattedValue(context.webRoot(),null)%>/images/spacer.gif" width="1" height="20" border="0" alt=""/></td></tr>
<tr>
<td colspan="2">
<img src="<%=context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("Monitor-DisplayLineChart",null))),(new URLParameterSet().addURLParameter(context.getFormattedValue("title",null),context.getFormattedValue("Active Sessions",null))).addURLParameter(context.getFormattedValue("ytitle",null),context.getFormattedValue("(count)",null)).addURLParameter(context.getFormattedValue("height",null),context.getFormattedValue("400",null)).addURLParameter(context.getFormattedValue("width",null),context.getFormattedValue("750",null)).addURLParameter(context.getFormattedValue("series0",null),context.getFormattedValue("Active Sessions",null)).addURLParameter(context.getFormattedValue("startDate",null),context.getFormattedValue(getObject("StartDateTimeStamp"),null)).addURLParameter(context.getFormattedValue("endDate",null),context.getFormattedValue(getObject("EndDateTimeStamp"),null)).addURLParameter(context.getFormattedValue("minimumGapSize",null),context.getFormattedValue(getObject("MinimumGapSize"),null))),null)%>" alt=""/>
</td>
</tr>
<tr><td colspan="2"><img src="<%=context.getFormattedValue(context.webRoot(),null)%>/images/spacer.gif" width="1" height="20" border="0" alt=""/></td></tr><% } %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("SessionChart"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",157,e);}if (_boolean_result) { %><tr><td colspan="2"><img src="<%=context.getFormattedValue(context.webRoot(),null)%>/images/spacer.gif" width="1" height="20" border="0" alt=""/></td></tr>
<tr>
<td colspan="2">
<img src="<%=context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("Monitor-DisplayLineChart",null))),(new URLParameterSet().addURLParameter(context.getFormattedValue("title",null),context.getFormattedValue("Active Requests",null))).addURLParameter(context.getFormattedValue("ytitle",null),context.getFormattedValue("(count)",null)).addURLParameter(context.getFormattedValue("height",null),context.getFormattedValue("400",null)).addURLParameter(context.getFormattedValue("width",null),context.getFormattedValue("750",null)).addURLParameter(context.getFormattedValue("series0",null),context.getFormattedValue("Active Requests",null)).addURLParameter(context.getFormattedValue("startDate",null),context.getFormattedValue(getObject("StartDateTimeStamp"),null)).addURLParameter(context.getFormattedValue("endDate",null),context.getFormattedValue(getObject("EndDateTimeStamp"),null)).addURLParameter(context.getFormattedValue("minimumGapSize",null),context.getFormattedValue(getObject("MinimumGapSize"),null))),null)%>" alt=""/>
</td>
</tr>
<tr><td colspan="2"><img src="<%=context.getFormattedValue(context.webRoot(),null)%>/images/spacer.gif" width="1" height="20" border="0" alt=""/></td></tr><% } %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("PerformanceChart"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",176,e);}if (_boolean_result) { %><tr><td colspan="2"><img src="<%=context.getFormattedValue(context.webRoot(),null)%>/images/spacer.gif" width="1" height="20" border="0" alt=""/></td></tr>
<tr>
<td colspan="2">
<img src="<%=context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("Monitor-DisplayLineChart",null))),(new URLParameterSet().addURLParameter(context.getFormattedValue("title",null),context.getFormattedValue("Average Response Times",null))).addURLParameter(context.getFormattedValue("ytitle",null),context.getFormattedValue("(ms)",null)).addURLParameter(context.getFormattedValue("height",null),context.getFormattedValue("400",null)).addURLParameter(context.getFormattedValue("width",null),context.getFormattedValue("750",null)).addURLParameter(context.getFormattedValue("series0",null),context.getFormattedValue("Avg. Response Time",null)).addURLParameter(context.getFormattedValue("startDate",null),context.getFormattedValue(getObject("StartDateTimeStamp"),null)).addURLParameter(context.getFormattedValue("endDate",null),context.getFormattedValue(getObject("EndDateTimeStamp"),null)).addURLParameter(context.getFormattedValue("minimumGapSize",null),context.getFormattedValue(getObject("MinimumGapSize"),null))),null)%>" alt=""/>
</td>
</tr>
<tr><td colspan="2"><img src="<%=context.getFormattedValue(context.webRoot(),null)%>/images/spacer.gif" width="1" height="20" border="0" alt=""/></td></tr><% } %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("PerformanceChart"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",195,e);}if (_boolean_result) { %><tr><td colspan="2"><img src="<%=context.getFormattedValue(context.webRoot(),null)%>/images/spacer.gif" width="1" height="20" border="0" alt=""/></td></tr>
<tr>
<td colspan="2">
<img src="<%=context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("Monitor-DisplayLineChart",null))),(new URLParameterSet().addURLParameter(context.getFormattedValue("title",null),context.getFormattedValue("CPU Usage",null))).addURLParameter(context.getFormattedValue("ytitle",null),context.getFormattedValue("(Percentage)",null)).addURLParameter(context.getFormattedValue("height",null),context.getFormattedValue("400",null)).addURLParameter(context.getFormattedValue("width",null),context.getFormattedValue("750",null)).addURLParameter(context.getFormattedValue("series0",null),context.getFormattedValue("CPU Usage",null)).addURLParameter(context.getFormattedValue("startDate",null),context.getFormattedValue(getObject("StartDateTimeStamp"),null)).addURLParameter(context.getFormattedValue("endDate",null),context.getFormattedValue(getObject("EndDateTimeStamp"),null)).addURLParameter(context.getFormattedValue("minimumGapSize",null),context.getFormattedValue(getObject("MinimumGapSize"),null))),null)%>" alt=""/>
</td>
</tr>
<tr><td colspan="2"><img src="<%=context.getFormattedValue(context.webRoot(),null)%>/images/spacer.gif" width="1" height="20" border="0" alt=""/></td></tr><% } %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("PerformanceChart"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",214,e);}if (_boolean_result) { %><tr><td colspan="2"><img src="<%=context.getFormattedValue(context.webRoot(),null)%>/images/spacer.gif" width="1" height="20" border="0" alt=""/></td></tr>
<tr>
<td colspan="2">
<img src="<%=context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("Monitor-DisplayLineChart",null))),(new URLParameterSet().addURLParameter(context.getFormattedValue("title",null),context.getFormattedValue("Load Factor",null))).addURLParameter(context.getFormattedValue("ytitle",null),context.getFormattedValue("(Probability)",null)).addURLParameter(context.getFormattedValue("height",null),context.getFormattedValue("400",null)).addURLParameter(context.getFormattedValue("width",null),context.getFormattedValue("750",null)).addURLParameter(context.getFormattedValue("series0",null),context.getFormattedValue("Probability",null)).addURLParameter(context.getFormattedValue("startDate",null),context.getFormattedValue(getObject("StartDateTimeStamp"),null)).addURLParameter(context.getFormattedValue("endDate",null),context.getFormattedValue(getObject("EndDateTimeStamp"),null)).addURLParameter(context.getFormattedValue("minimumGapSize",null),context.getFormattedValue(getObject("MinimumGapSize"),null))),null)%>" alt=""/>
</td>
</tr>
<tr><td colspan="2"><img src="<%=context.getFormattedValue(context.webRoot(),null)%>/images/spacer.gif" width="1" height="20" border="0" alt=""/></td></tr><% } %><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("PerformanceChart"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",233,e);}if (_boolean_result) { %><tr><td colspan="2"><img src="<%=context.getFormattedValue(context.webRoot(),null)%>/images/spacer.gif" width="1" height="20" border="0" alt=""/></td></tr>
<tr>
<td colspan="2">
<img src="<%=context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("Monitor-DisplayLineChart",null))),(new URLParameterSet().addURLParameter(context.getFormattedValue("title",null),context.getFormattedValue("Thread Count",null))).addURLParameter(context.getFormattedValue("ytitle",null),context.getFormattedValue("(count)",null)).addURLParameter(context.getFormattedValue("height",null),context.getFormattedValue("400",null)).addURLParameter(context.getFormattedValue("width",null),context.getFormattedValue("750",null)).addURLParameter(context.getFormattedValue("series0",null),context.getFormattedValue("System Threads",null)).addURLParameter(context.getFormattedValue("startDate",null),context.getFormattedValue(getObject("StartDateTimeStamp"),null)).addURLParameter(context.getFormattedValue("endDate",null),context.getFormattedValue(getObject("EndDateTimeStamp"),null)).addURLParameter(context.getFormattedValue("minimumGapSize",null),context.getFormattedValue(getObject("MinimumGapSize"),null))),null)%>" alt=""/>
</td>
</tr>
<tr><td colspan="2"><img src="<%=context.getFormattedValue(context.webRoot(),null)%>/images/spacer.gif" width="1" height="20" border="0" alt=""/></td></tr><% } %></table>
</td>
</tr>
</table>
</td>
</tr><% } %></table>
<!-- /Main Content --><% printFooter(out); %>