<%@  page buffer="none" import="java.util.*,java.io.*,com.intershop.beehive.core.internal.template.*,com.intershop.beehive.core.internal.template.isml.*,com.intershop.beehive.core.capi.log.*,com.intershop.beehive.core.capi.resource.*,com.intershop.beehive.core.capi.util.UUIDMgr,com.intershop.beehive.core.capi.util.XMLHelper,com.intershop.beehive.foundation.util.*,com.intershop.beehive.core.internal.url.*,com.intershop.beehive.core.internal.resource.*,com.intershop.beehive.core.internal.wsrp.*,com.intershop.beehive.core.capi.pipeline.PipelineDictionary,com.intershop.beehive.core.capi.naming.NamingMgr,com.intershop.beehive.core.capi.pagecache.PageCacheMgr,com.intershop.beehive.core.capi.request.SessionMgr,com.intershop.beehive.core.internal.request.SessionMgrImpl,com.intershop.beehive.core.pipelet.PipelineConstants" extends="com.intershop.beehive.core.internal.template.AbstractTemplate" %><% 
boolean _boolean_result=false;
TemplateExecutionConfig context = getTemplateExecutionConfig();
createTemplatePageConfig(context.getServletRequest());
printHeader(out);
 %><% %><%@ page contentType="text/html;charset=utf-8" %><%setEncodingType("text/html"); %><tr><% _boolean_result=false;try {_boolean_result=((Boolean)((disableErrorMessages().isDefined(getObject("ERROR_User"))))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",3,e);}if (_boolean_result) { %><td class="table_detail e error" valign="top"><% {String value = null;try{value=context.getFormattedValue(getObject("LocalServer:Name"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {4}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>&nbsp;</td>
<td class="table_detail e" valign="top"><% {out.write(localizeISText("monitor.NA.table_detail","",null,null,null,null,null,null,null,null,null,null,null));} %></td>
<td class="table_detail e" valign="top" align="right"><% {out.write(localizeISText("monitor.NA.table_detail","",null,null,null,null,null,null,null,null,null,null,null));} %>&nbsp;</td>
<td class="table_detail e" valign="top"><% {out.write(localizeISText("monitor.NA.table_detail","",null,null,null,null,null,null,null,null,null,null,null));} %></td> 
<td class="table_detail e" valign="top" align="right"><% {out.write(localizeISText("monitor.NA.table_detail","",null,null,null,null,null,null,null,null,null,null,null));} %>&nbsp;</td>
<td class="table_detail e" valign="top"><% {out.write(localizeISText("monitor.NA.table_detail","",null,null,null,null,null,null,null,null,null,null,null));} %></td>
<td class="table_detail e" valign="top" align="right"><% {out.write(localizeISText("monitor.NA.table_detail","",null,null,null,null,null,null,null,null,null,null,null));} %>&nbsp;</td>
<td class="table_detail e" valign="top" align="right"><% {out.write(localizeISText("monitor.NA.table_detail","",null,null,null,null,null,null,null,null,null,null,null));} %>&nbsp;</td>
<td class="table_detail e" valign="top" align="right"><% {out.write(localizeISText("monitor.NA.table_detail","",null,null,null,null,null,null,null,null,null,null,null));} %>&nbsp;</td>
<td class="table_detail" valign="top" align="right"><% {out.write(localizeISText("monitor.NA.table_detail","",null,null,null,null,null,null,null,null,null,null,null));} %>&nbsp;</td><% } else { %><td class="table_detail e" valign="top"><% {String value = null;try{value=context.getFormattedValue(getObject("LocalServer:Name"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {16}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %></td>
<td class="table_detail e" valign="top"><% {String value = null;try{value=context.getFormattedValue(getObject("LocalServer:Host"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {18}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>&nbsp;</td>
<td class="table_detail e" valign="top" align="right"><% {String value = null;try{value=context.getFormattedValue(getObject("LocalServer:Port"),"#",null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {19}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>&nbsp;</td>
<td class="table_detail e" valign="top"><% {String value = null;try{value=context.getFormattedValue(getObject("LocalServer:InstallationID"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {20}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>&nbsp;</td>
<td class="table_detail e" valign="top" align="right"><% {String value = null;try{value=context.getFormattedValue(getObject("Process_PID"),"#",null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {21}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>&nbsp;</td>
<td class="table_detail e" valign="top"><% {String value = null;try{value=context.getFormattedValue(getObject("LocalServer:StartDate"),"MM/dd/yyyy - HH:mm:ss",null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {22}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>&nbsp;</td>
<td class="table_detail e" valign="top" align="right"><% {String value = null;try{value=context.getFormattedValue(getObject("Process_CpuUsage"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {23}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>%&nbsp;</td> 
<td class="table_detail e" valign="top" align="right"><% {String value = null;try{value=context.getFormattedValue(getObject("JVM_HeapUsage"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {24}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>%&nbsp;</td> 
<td class="table_detail e" valign="top" align="right"><% {String value = null;try{value=context.getFormattedValue((new Double( ((Number) getObject("Process_TotalSize")).doubleValue() / ((Number) new Double(1024)).doubleValue() /((Number) new Double(1024)).doubleValue())),"#.##",null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {25}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %> MB&nbsp;</td>
<td class="table_detail" valign="top" align="right"><% {String value = null;try{value=context.getFormattedValue(getObject("ActiveSessionCount"),null,null);}catch(Exception e){value=null;Logger.error(this,"ISPRINT has an invalid expression. Returning empty string. Line: {26}",e);}if (value==null) value="";value = encodeString(value);out.write(value);} %>&nbsp;</td><% } %></tr><% printFooter(out); %>