<%@  page buffer="none" import="java.util.*,java.io.*,com.intershop.beehive.core.internal.template.*,com.intershop.beehive.core.internal.template.isml.*,com.intershop.beehive.core.capi.log.*,com.intershop.beehive.core.capi.resource.*,com.intershop.beehive.core.capi.util.UUIDMgr,com.intershop.beehive.core.capi.util.XMLHelper,com.intershop.beehive.foundation.util.*,com.intershop.beehive.core.internal.url.*,com.intershop.beehive.core.internal.resource.*,com.intershop.beehive.core.internal.wsrp.*,com.intershop.beehive.core.capi.pipeline.PipelineDictionary,com.intershop.beehive.core.capi.naming.NamingMgr,com.intershop.beehive.core.capi.pagecache.PageCacheMgr,com.intershop.beehive.core.capi.request.SessionMgr,com.intershop.beehive.core.internal.request.SessionMgrImpl,com.intershop.beehive.core.pipelet.PipelineConstants" extends="com.intershop.beehive.core.internal.template.AbstractTemplate" %><% 
boolean _boolean_result=false;
TemplateExecutionConfig context = getTemplateExecutionConfig();
createTemplatePageConfig(context.getServletRequest());
printHeader(out);
 %><% %><%! protected Boolean printTemplateMarker() { return Boolean.TRUE; } %><%%><%@ page contentType="text/html;charset=utf-8" %><%response.setHeader(TemplateConstants.PERSONALIZED_HEADER, "1");setEncodingType("text/html"); %><% {out.flush();processLocalIncludeByServer((com.intershop.beehive.core.capi.request.ServletResponse)response,"modules/Modules", null, "2");} %><% {out.flush();processLocalIncludeByServer((com.intershop.beehive.core.capi.request.ServletResponse)response,"checkout/common/HeaderProgressBar", null, "4");} %><div class="marketing-area"><% processOpenTag(response, pageContext, "marketingslot", new TagParameter[] {
new TagParameter("id","baseMarketing")}, 7); %></div>
<h1><% {out.write(localizeISText("checkout.validate_address.header","",null,null,null,null,null,null,null,null,null,null,null));} %></h1><% URLPipelineAction action77 = new URLPipelineAction(context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewCheckoutAddressBook-AddressValidation",null)))),null));String site77 = null;String serverGroup77 = null;String actionValue77 = context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewCheckoutAddressBook-AddressValidation",null)))),null);if (site77 == null){  site77 = action77.getDomain();  if (site77 == null)  {      site77 = com.intershop.beehive.core.capi.request.Request.getCurrent().getRequestSite().getDomainName();  }}if (serverGroup77 == null){  serverGroup77 = action77.getServerGroup();  if (serverGroup77 == null)  {      serverGroup77 = com.intershop.beehive.core.capi.request.Request.getCurrent().getRequestSite().getServerGroup();  }}out.print("<form");out.print(" method=\"");out.print("post");out.print("\"");out.print(" action=\"");out.print(context.getFormattedValue(url(true,(new URLPipelineAction(context.getFormattedValue("ViewCheckoutAddressBook-AddressValidation",null)))),null));out.print("\"");out.print(">");out.print(context.prepareWACSRFTag(actionValue77, site77, serverGroup77,true)); %><div class="row">
<div class="col-md-8"><% _boolean_result=false;try {_boolean_result=((Boolean)(((((Boolean) (disableErrorMessages().isDefined(getObject("BillingAddressValidationSuggestedAddresses")))).booleanValue() || ((Boolean) (disableErrorMessages().isDefined(getObject("BillingAddressValidationFailed")))).booleanValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",15,e);}if (_boolean_result) { %><h2><% {out.write(localizeISText("checkout.validate_address.billing","",null,null,null,null,null,null,null,null,null,null,null));} %></h2><% processOpenTag(response, pageContext, "addresssuggest", new TagParameter[] {
new TagParameter("targetaddress",getObject("InvoiceToAddressBO")),
new TagParameter("suggestedaddresses",getObject("BillingAddressValidationSuggestedAddresses")),
new TagParameter("formprefix","billingAddress"),
new TagParameter("sourceaddress",getObject("InvoiceToAddressBO")),
new TagParameter("locale",getObject("CurrentSession:Locale")),
new TagParameter("validateaddressnoresultmessagekey","checkout.validate_address.no_result")}, 17); %><% } %><% _boolean_result=false;try {_boolean_result=((Boolean)(((((Boolean) (disableErrorMessages().isDefined(getObject("ShippingAddressValidationSuggestedAddresses")))).booleanValue() || ((Boolean) (disableErrorMessages().isDefined(getObject("ShippingAddressValidationFailed")))).booleanValue()) ? Boolean.TRUE : Boolean.FALSE))).booleanValue();} catch (Exception e) {Logger.debug(this,"Boolean expression in line {} could not be evaluated. False returned. Consider using the 'isDefined' ISML function.",20,e);}if (_boolean_result) { %><h2><% {out.write(localizeISText("checkout.validate_address.shipping","",null,null,null,null,null,null,null,null,null,null,null));} %></h2><% processOpenTag(response, pageContext, "addresssuggest", new TagParameter[] {
new TagParameter("targetaddress",getObject("ShipToAddressBO")),
new TagParameter("suggestedaddresses",getObject("ShippingAddressValidationSuggestedAddresses")),
new TagParameter("formprefix","shippingAddress"),
new TagParameter("sourceaddress",getObject("ShipToAddressBO")),
new TagParameter("locale",getObject("CurrentSession:Locale")),
new TagParameter("validateaddressnoresultmessagekey","checkout.validate_address.no_result")}, 22); %><% } %><div class="form-group">
<button name="saveAddAnother" class="btn btn-default" type="submit"><% {out.write(localizeISText("checkout.validate_address.save_add_another","",null,null,null,null,null,null,null,null,null,null,null));} %></button>
</div>
</div>
<div class="col-md-4">
<h2><% {out.write(localizeISText("checkout.order_details.heading","",null,null,null,null,null,null,null,null,null,null,null));} %></h2>
<div class="cost-summary"><% {out.flush();processLocalIncludeByServer((com.intershop.beehive.core.capi.request.ServletResponse)response,"checkout/common/widgets/CostSummary", null, "33");} %><button name="continue" class="btn btn-lg btn-block btn-primary" type="submit"><% {out.write(localizeISText("checkout.button.label","",null,null,null,null,null,null,null,null,null,null,null));} %></button>
</div><% {out.flush();processLocalIncludeByServer((com.intershop.beehive.core.capi.request.ServletResponse)response,"checkout/common/widgets/SecurityPrivacyPolicyLink.isml", null, "36");} %></div>
</div><% out.print("</form>"); %><% printFooter(out); %>